### ISSUE TITLE
Small text on High resolution screens

### ISSUE THREAD

**Issue by vidia** [PCGen/pcgen#1606]
I am having an issue where the size of all the text and buttons is incredibly small, and don't respond to changing the resolution in Windows display settings. 

I am running PCGen on a Surface Book. 

Is there anything that can be done about this or is a code change required?

**Comment by LegacyKing** [comment]
This is a Java issue. @cpmeister is working on this issue.

**Comment by vidia** [comment]
@cpmeister Is there an update on this? Would you like any help on it (not that I am familiar with this codebase)

**Comment by LegacyKing** [comment]
@vidia if you are willing to help, that would be appreciated. The code monkey leading the project has not been actively communicating for some time. One of the fun things about open source projects, real life happens unexpectedly.  The solution that was planned was re-writing the entire UI in the JavaFX (java 8) method, migrating from our current Java Swing. Initial work was submitted for review, but it is far from complete.

**Comment by LegacyKing** [comment]
Okay, Late update, but we pulled in a change from a user that should make this easier in the 6.07.03 release. Coming soon (tm)

**Comment by boredgame16** [comment]
I was able to workaround this issue by going into the compatibility properties of the PCGen shortcut and setting the "Override high DPI scaling behavior" to System. This was tested on Windows 10.

**Comment by LegacyKing** [comment]
Issue moved to JIRA - FAQ updated on the WIKI. Closing out as we have a workaround.
