### ISSUE TITLE
Can't create level 1 summoner

### ISSUE THREAD

**Issue by Nolski** [PCGen/pcgen#1776]
So in the process of creating a level 1 summoner, I needed to also create my Eidolon. I created it from the Companions tab of my summoner character, rolled up it's stats and skills and then needed to do the Eidolon Selection. On the Feats and Abilities -> Racial Abilities -> Eidolon Selection menu, there was only one selection available (Standard Eidolon) but I was not able to select it due to the output below.

Any idea of how I can fix this?

```
Requirements: All of (var: IsCompanion exactly 1, var: EidolonDefault exactly 1)
```

**Comment by LegacyKing** [comment]
Which version?

**Comment by Nolski** [comment]
`6.06.01`

I'm running the .jar on OSX with java `1.8.0_101-b13`.

**Comment by Nolski** [comment]
It turns out if you create an Eidolon through the companions tab it doesn't recognize it as a companion to the character where it's created through so this is really a non issue.

**Comment by LegacyKing** [comment]
Uh, companion tab is the only method to get it recognized. Give the latest dev autobuild a go, that *should* correct the problem.

**Comment by Nolski** [comment]
That could be it. For those who might encounter this problem the way I got around it was on the summary tab under the "Things to be done" window, there was a link to Select Eidolon (I think that was it) and I recreated my eidolon that way.

It could be that I just created a companion that was an Eidolon the first way? It's hard to say :\
