### ISSUE TITLE
Elemental Spell Metamagic Feat not functioning 6.06.01

### ISSUE THREAD

**Issue by Sadler0000** [PCGen/pcgen#1787]
The program will not let me add "Elemental Spell" Metamagic feat to a spell (example Fireball). It does not even come up in the list of "Add Spell with Metamagic Feats window, but I know I have taken this feat with the Cold descriptor selected. 

I have installed PCGen on several different computers and tried older versions of PCGEN and I run into the same issue.

Any help will be appreciated!

**Comment by LegacyKing** [comment]
Investigating...

**Comment by LegacyKing** [comment]
@Zaister Is there a restriction on what Metamagic can be selected by the code? Elemental Spell with the Add Level stuff is on a VISIBLE:NO line. Did we determine it needs a YES or EXPORT?

**Comment by LegacyKing** [comment]
Needs a Jira Ticket, and testing.

**Comment by Sadler0000** [comment]
Is this something I need to do or are you doing it? 

BTW thank you for your help! I love this program!

**Comment by LegacyKing** [comment]
https://github.com/PCGen/pcgen/pull/1810
