### ISSUE TITLE
Add more rolling methods

### ISSUE THREAD

**Issue by Kosyne** [PCGen/pcgen#1821]
I could be wrong, but I believe older version had more than just 'Classic, Standard, and Heroic' dice rolling options.

I personally would like to see 4d6 reroll 1's (pretty sure it used to be in PCGen)

However, I think a better solution might be to allow users to add their own expressions into the dice roller via preferences or similar.

**Comment by LegacyKing** [comment]
You can have as many as you'd like. I haven't removed any options.

**Comment by LegacyKing** [comment]
3.5e still has all it's options:
ROLLMETHOD:3d6						METHOD:3d6
ROLLMETHOD:4d4						METHOD:4d4
ROLLMETHOD:4d6 drop lowest				METHOD:roll(4,6,top(3))
ROLLMETHOD:4d6, reroll 1's				METHOD:roll(4,6,reroll(1))
ROLLMETHOD:4d6, reroll 1's, drop the lowest	METHOD:roll(4,6,top(3),reroll(1))
ROLLMETHOD:5d6 drop 2 lowest				METHOD:roll(5,6,top(3))

**Comment by LegacyKing** [comment]
And Pathfinder (And society) still has it's options:

ROLLMETHOD:Standard (4d6 drop lowest)	METHOD:roll(4,6,top(3))
ROLLMETHOD:Classic (3d6)			METHOD:3d6
ROLLMETHOD:Heroic (2d6+6)			METHOD:2d6+6

**Comment by Kosyne** [comment]
Ah, that must be it, you've tied rolling options to gametypes...

I was wanting one of those 3.5e methods for my pathfinder stuff.

**Comment by LegacyKing** [comment]
Nothing for the team to handle. Closing

**Comment by gameguy95** [comment]
Out of curiosity, what file would these be stored in if I wanted to copy the 3.5e methods into the Pathfinder stuff or add my own methods? For example, my current DM has us roll 5d6, reroll 1s and 2s, and then take the best 3 of those. If I wanted to implement that as a rolling method, is there a way for me to do so?

**Comment by LegacyKing** [comment]
Miscinfo.lst found in the system/gamemode

#
# Dice rolling methods for character creation
#
ROLLMETHOD:3d6						METHOD:3d6
ROLLMETHOD:4d4						METHOD:4d4
ROLLMETHOD:4d6 drop lowest				METHOD:roll(4,6,top(3))
ROLLMETHOD:4d6, reroll 1's				METHOD:roll(4,6,reroll(1))
ROLLMETHOD:4d6, reroll 1's, drop the lowest	METHOD:roll(4,6,top(3),reroll(1))
ROLLMETHOD:5d6 drop 2 lowest				METHOD:roll(5,6,top(3))

**Comment by gameguy95** [comment]
So, for my case of roll 5d6, reroll 1s and 2s, and then drop two lowest, would this be the correct way to implement it? 
ROLLMETHOD:5d6, reroll 1's and 2's, drop the lowest 2	METHOD:roll(5,6,top(3),reroll(2))

**Comment by gameguy95** [comment]
It seems that simply copy and pasting this into the miscinfo.lst file under System/Gamemodes/Pathfinder results in errors that prevent the creation of new characters. 
"10:24:21.337 SEVERE Thread-10 GameMode:240 Could not find roll method 'Standard (4d6 drop lowest)' while loading game mode Pathfinder_RPG"
