### ISSUE TITLE
Racial Subtypes

### ISSUE THREAD

**Issue by scottz657** [PCGen/pcgen#1887]
In the latest release, I am unable to select a racial subtype for several different races, namely Dhampirs, and Half-Elves.

**Comment by LegacyKing** [comment]
Hi, can you supply a character .pcg file, so I can load the same source you are? Send it to help@pcgen.org.

Thanks

**Comment by scottz657** [comment]
Here it is

________________________________

**Comment by LegacyKing** [comment]
Where?

**Comment by scottz657** [comment]
I have attached the file to this email.

________________________________

**Comment by scottz657** [comment]
I can't upload it on github, I can send it by email though check your inbox

**Comment by LegacyKing** [comment]
I have... help@pcgen.org -- nothing there yet.

**Comment by LegacyKing** [comment]
![image](https://cloud.githubusercontent.com/assets/2759875/20645955/936985ae-b423-11e6-818b-f29344627d4b.png)

So, uh, what is missing again???

**Comment by scottz657** [comment]
Idk what's up because this is what I see
![screenshot 1](https://cloud.githubusercontent.com/assets/23664461/20646012/4ceca7ae-b42e-11e6-9211-ae0a6dfdec22.png)

**Comment by LegacyKing** [comment]
This tells me the issue is fixed in the latest version. Grab an autobuild, or the 6.07.00 version. Either *should* resolve your issue.

**Comment by scottz657** [comment]
kk thnx
