### ISSUE TITLE
Incorrect formula for Pathfinder»Paizo»Ultimate Equipment»ue_equipmods.lst “Greenwood”

### ISSUE THREAD

**Issue by Ghostbird** [PCGen/pcgen#2005]
Formula is listed as weight × 50gp.
However http://www.d20pfsrd.com/equipment---final/special-materials#TOC-Greenwood says:
To determine the price of a greenwood item, use the original weight but add 50 gp per pound to the price of a *masterwork version of that item*. 

So cost should be (BASECOST)+(MWORKCOST)+WT*50

I think it somewhere needs this added:
BONUS:ITEMCOST|TYPE.AMMUNITION|6 BONUS:ITEMCOST|TYPE.WEAPON|300|!PRETYPE:1,Shield BONUS:ITEMCOST|TYPE.SHIELD|150

**Comment by LegacyKing** [comment]
The referenced website cannot be used officially for corrections. We need to verify from the actual publisher website or book.

I could be wrong, but I don't think MWORKCOST is a legal item. At least not in the JEP convention. This should be plausible to accomplish with the new formula system once we determine how to get the equipment cost integrated into the UI.

**Comment by LegacyKing** [comment]
@thpr  what do you think? -- LOCAL for BASECOST, toss a MasterworkPrice based upon item type if(MasterworkItem=="True",300,0) we'd have to make Weight a local var to reference, and tie into the UI as well... The item customizer will need one of those code controls to switch the various options for weight, and cost.

**Comment by Ghostbird** [comment]
@LegacyKing The functionality is already there! It's used for Darkwood in the Core Rulebook sources. It's done by giving the item a "Bonus" that incurs a cost, dependent on type, as I mentioned above, using this data:
BONUS:ITEMCOST|TYPE.AMMUNITION|6 BONUS:ITEMCOST|TYPE.WEAPON|300|!PRETYPE:1,Shield BONUS:ITEMCOST|TYPE.SHIELD|150

As you can see, this adds 6gp to the cost of an ammunition type item, 300 to a non-shield pretyped weapon type item, or 150 to the cost of a shield type item.

I made a fork, and tried to add it myself, to make a PR, but I did something wrong, and it didn't work. I don't know the .lst format well enough.

The only thing that needs to be done is add those "bonuses" to the material, in the correct way.

**Comment by LegacyKing** [comment]
Included this.
