### ISSUE TITLE
add square to spells slots

### ISSUE THREAD

**Issue by sirwimelef** [PCGen/pcgen#2041]
Hi,
I don’t know if it’s the correct place for suggestions, but here it go.
Add empty squares next to the spells slots when you export the character
That will be very useful to track how many spells u used each day
Now you have:
"Arcanist Spells Prepared  
Spell slots per day - 1st = 6, 2nd = 4, 3rd = 0, 4th = 0, 5th = 0, 6th = 0, 7th = 0, 8th = 0, 9th = 0 "

So change this for something like: 
Spell slots per day
1st-	☐☐☐☐☐☐
2nd-☐☐☐☐

**Comment by LegacyKing** [comment]
Are you able to make this an Output Sheet request on our tracker? https://pcgenorg.atlassian.net
