### ISSUE TITLE
Divine Bond (Celestial spirit) not working properly for Divine Hunter Paladins

### ISSUE THREAD

**Issue by eplossl** [PCGen/pcgen#2048]
When a Paladin is built as a Divine Hunter and reaches level 5, he gains the Divine Bond feature as would most paladins.  Unlike a normal paladin, however, this can only be implemented as a bonus to the paladin's weapon.  

The issue I am finding is that to make this work, the developers seem to have implemented this as a new ability called a Celestial Spirit.  The part which isn't working is that, even when working with a level 5 character, it shows that the ability cannot be used.  See the following image:

![image](https://cloud.githubusercontent.com/assets/11776328/22400379/f41a2c9e-e580-11e6-8bcd-effb2faefc19.png)

At level 5, it should indicate that I can use the ability once per day and adds a +1 enhancement bonus.  I have tested this through 8th level but the enhancement bonus (which should be +2 @ 8th level) remains +0 in the description of the ability.

I tried removing the Divine Hunter feature (from Ultimate Combat), and checked the Divine Bond feature for the paladin of the same level.  Interestingly, the Divine Bond feature does not seem to be showing up at all, which I suspect is why this feature isn't calculating properly for my level 5 Divine Hunter Paladin.  

See http://www.d20pfsrd.com/classes/core-classes/paladin#TOC-Divine-Bond-Sp- for information about the Divine Bond feature on the regular Paladin.

**Comment by LegacyKing** [comment]
Any chance you can input this into the bug tracker here: https://pcgenorg.atlassian.net ???

I'll take a gander at it in a bit.

**Comment by LegacyKing** [comment]
Also, Divine Bond has two forms - Celestial Spirit and the Mount. Which is why it appears as it does.

**Comment by eplossl** [comment]
I have been digging into it some more...  The Divine bond takes two forms, as you noted.  For the basic Paladin, you actually have to select the correct version of it.  However, since the Divine Hunter replaces that feature with only the Celestial Spirit version (you lose the possibility of a mount), for some reason the system doesn't seem to be detecting the fact that the Paladin has the Divine Bond feature present and seems to be missing the data.

**Comment by eplossl** [comment]
Got it set up over there as requested.

**Comment by LegacyKing** [comment]
https://github.com/PCGen/pcgen/pull/2049
