### ISSUE TITLE
Pcgen on linux

### ISSUE THREAD

**Issue by snoopyreed79** [PCGen/pcgen#2416]
Hello i have never used a forum other then to read it. With that said I am trying to install pcgen on my linux os. I think I get it on there then try to use it and the pcgen tells me i need java. I have java installed. I am new a useing linux os the platform I have is zorin witch is based of ubuntu any hEl would be great fully appreciated. 
Thanks for your time 
Snoopy Reed

**Comment by Nylanfs** [comment]
I think these two forum posts will help.

http://zoringroup.com/forum/viewtopic.php?f=5&t=1734

http://zoringroup.com/forum/viewtopic.php?f=5&t=1812&start=10

**Comment by Nylanfs** [comment]
I believe this forum post will help.
http://zoringroup.com/forum/viewtopic.php?f=5&t=1734
 
Paul A. Grosse 

    On Wednesday, March 1, 2017 8:05 AM, snoopyreed79 <notifications@github.com> wrote:
 

 Hello i have never used a forum other then to read it. With that said I am trying to install pcgen on my linux os. I think I get it on there then try to use it and the pcgen tells me i need java. I have java installed. I am new a useing linux os the platform I have is zorin witch is based of ubuntu any hEl would be great fully appreciated.
Thanks for your time
Snoopy Reed—
