### ISSUE TITLE
Simplify repeating code lines using loop to pull in variable element

### ISSUE THREAD

**Issue by LearnTribe** [PCGen/pcgen#2605]
Adding this as reminder to look at improving data structure for isg_abilities.lst
Aligned Class feature for Evangelist was updated to add range of classes, but rather than repeating same set of details 30+ times to cover all classes would be better to write a for/next loop with string of playable classes. I'll tackle this once I've got a better handle on data structure and time to do proper testing but happy if someone else with more experience wants to pick it up. It's not urgent as current solution works and covers all base classes, but just feels inelegant and isn't future proof.

**Comment by LegacyKing** [comment]
For/next loop isn't possible in data files. Welcome to my world. Though we are improving this...

**Comment by LegacyKing** [comment]
I would suggest looking to use the new formula system as a potential method to make this future proof.

**Comment by LearnTribe** [comment]
Ah well, it was a nice idea. It just felt like using a string containing the available classes and looping through them was a logical way to approach the problem, but to be fair I hadn't gotten any further than thinking how it might be tackled. I'll take a look at the formula system - I guess there must be dozens of places where this sort of repetitive issue crops up.
