### ISSUE TITLE
Errors on gui2 compiling

### ISSUE THREAD

**Issue by FoxShot** [PCGen/pcgen#2659]
Got these compiler errors:

:makeplugindirs
:clean-plugins
:cleanRoot UP-TO-DATE
:clean
:copyMasterSheets
:compileJava
warning: [options] bootstrap class path not set in conjunction with -source 1.8
/pcgen/code/src/java/pcgen/gui2/util/treeview/TreeViewTableModel.java:285: error: TreeViewTableModel.TreeViewNode is not abstract and does not override abstract method children() in TreeTableNode
        private final class TreeViewNode extends JTree.DynamicUtilTreeNode
                      ^
/pcgen/code/src/java/pcgen/gui2/util/treeview/TreeViewTableModel.java:349: error: no suitable method found for binarySearch(Vector<TreeNode>,TreeViewTableModel<E>.TreeViewNode,Comparator<Row>)
                                                int index = Collections.binarySearch(children, child, mostRecentComparator);
                                                                       ^
    method Collections.<T#1>binarySearch(List<? extends Comparable<? super T#1>>,T#1) is not applicable
      (cannot infer type-variable(s) T#1
        (actual and formal argument lists differ in length))
    method Collections.<T#2>binarySearch(List<? extends T#2>,T#2,Comparator<? super T#2>) is not applicable
      (inference variable T#2 has incompatible bounds
        upper bounds: Row,Object
        lower bounds: TreeViewTableModel<E>.TreeViewNode,TreeNode)
  where E,T#1,T#2 are type-variables:
    E extends Object declared in class TreeViewTableModel
    T#1 extends Object declared in method <T#1>binarySearch(List<? extends Comparable<? super T#1>>,T#1)
    T#2 extends Object declared in method <T#2>binarySearch(List<? extends T#2>,T#2,Comparator<? super T#2>)
/pcgen/code/src/java/pcgen/gui2/util/treeview/TreeViewTableModel.java:446: error: no suitable method found for binarySearch(Vector<TreeNode>,TreeViewTableModel<E>.TreeViewNode,Comparator<Row>)
                        int index = Collections.binarySearch(children, newchild, mostRecentComparator);
                                               ^
    method Collections.<T#1>binarySearch(List<? extends Comparable<? super T#1>>,T#1) is not applicable
      (cannot infer type-variable(s) T#1
        (actual and formal argument lists differ in length))
    method Collections.<T#2>binarySearch(List<? extends T#2>,T#2,Comparator<? super T#2>) is not applicable
      (inference variable T#2 has incompatible bounds
        upper bounds: Row,Object
        lower bounds: TreeViewTableModel<E>.TreeViewNode,TreeNode)
  where E,T#1,T#2 are type-variables:
    E extends Object declared in class TreeViewTableModel
    T#1 extends Object declared in method <T#1>binarySearch(List<? extends Comparable<? super T#1>>,T#1)
    T#2 extends Object declared in method <T#2>binarySearch(List<? extends T#2>,T#2,Comparator<? super T#2>)
/pcgen/code/src/java/pcgen/gui2/util/treeview/TreeViewTableModel.java:501: error: no suitable method found for sort(Comparator<Row>)
                                children.sort(comparator);
                                        ^
    method List.sort(Comparator<? super TreeNode>) is not applicable
      (argument mismatch; Comparator<Row> cannot be converted to Comparator<? super TreeNode>)
    method Vector.sort(Comparator<? super TreeNode>) is not applicable
      (argument mismatch; Comparator<Row> cannot be converted to Comparator<? super TreeNode>)
/pcgen/code/src/java/pcgen/gui2/util/treetable/DefaultTreeTableNode.java:33: error: DefaultTreeTableNode is not abstract and does not override abstract method children() in TreeTableNode
public class DefaultTreeTableNode extends DefaultMutableTreeNode implements TreeTableNode
       ^
/pcgen/code/src/java/pcgen/gui2/tabs/CompanionInfoTab.java:875: error: children() in DefaultMutableTreeNode cannot implement children() in TreeTableNode
                private class CompanionNode extends DefaultTreeTableNode
                        ^
  return type Enumeration<TreeNode> is not compatible with Enumeration<TreeTableNode>
/pcgen/code/src/java/pcgen/gui2/tabs/CompanionInfoTab.java:903: error: children() in DefaultMutableTreeNode cannot implement children() in TreeTableNode
                private class CompanionTypeNode extends DefaultTreeTableNode implements ReferenceListener<String>
                        ^
  return type Enumeration<TreeNode> is not compatible with Enumeration<TreeTableNode>
/pcgen/code/src/java/pcgen/gui2/tabs/CompanionInfoTab.java:1019: error: children() in DefaultMutableTreeNode cannot implement children() in TreeTableNode
                class RootNode extends DefaultTreeTableNode implements MapListener<String, Integer>, ListListener<CompanionFacade>
                ^
  return type Enumeration<TreeNode> is not compatible with Enumeration<TreeTableNode>
/pcgen/code/src/java/pcgen/gui2/util/treetable/DefaultSortableTreeTableNode.java:32: error: DefaultSortableTreeTableNode is not abstract and does not override abstract method children() in TreeTableNode
public class DefaultSortableTreeTableNode extends DefaultTreeTableNode
       ^
/pcgen/code/src/java/pcgen/gui2/util/treetable/DefaultSortableTreeTableNode.java:66: error: no suitable method found for sort(Comparator<Row>)
            children.sort(comparator);
                    ^
    method List.sort(Comparator<? super TreeNode>) is not applicable
      (argument mismatch; Comparator<Row> cannot be converted to Comparator<? super TreeNode>)
    method Vector.sort(Comparator<? super TreeNode>) is not applicable
      (argument mismatch; Comparator<Row> cannot be converted to Comparator<? super TreeNode>)
/pcgen/code/src/java/pcgen/gui2/tabs/ability/AbilityTreeTableModel.java:136: error: children() in DefaultMutableTreeNode cannot implement children() in TreeTableNode
        private class RootTreeTableNode extends DefaultSortableTreeTableNode implements ListListener<AbilityCategoryFacade>
                ^
  return type Enumeration<TreeNode> is not compatible with Enumeration<TreeTableNode>
/pcgen/code/src/java/pcgen/gui2/tabs/ability/AbilityTreeTableModel.java:185: error: children() in DefaultMutableTreeNode cannot implement children() in TreeTableNode
        private class CategoryTreeTableNode extends DefaultSortableTreeTableNode implements ListListener<AbilityFacade>
                ^
  return type Enumeration<TreeNode> is not compatible with Enumeration<TreeTableNode>
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
12 errors
1 warning
:compileJava FAILED

**Comment by grimreaper** [comment]
What version of Java are you using to compile? This error message looks something like what happens when you use a too-new or too-old version of javac.

**Comment by FoxShot** [comment]
javac -version
produces:
javac 9-internal

Does gradlew have any option for choosing the compiler?

**Comment by grimreaper** [comment]
You need to set JAVA_HOME to a Java 8 compiler. While I am working on supporting Java 9 you'll need to wait for some patches to land. 
Note that Java 9 is in pre release and in general you're expected to be able to help fix issues encountered when you are using it.

**Comment by FoxShot** [comment]
Changing compiler to version 8 solved this. Thank you.

**Comment by FoxShot** [comment]
Using version 8 fixed the compiling but now I have problems with e.g. saving a character:
SEVERE AWT-EventQueue-0 PCGenFrame:714 Index: 0, Size: 0
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
...

**Comment by grimreaper** [comment]
#2601 fixes that issue

**Comment by grimreaper** [comment]
#2661 will fix some other unrelated issues

**Comment by LegacyKing** [comment]
Both are in... closing this.
