### ISSUE TITLE
Volly Shot Team Work feat prerequisites allowing selection

### ISSUE THREAD

**Issue by nuwar** [PCGen/pcgen#2782]
Volley Fire Type: Combat. 

Teamwork Requirements: all of ( at least 1 Point Blank Shot FEAT ) and at least: Point-Blank Shot.

This appears to require both Point-Blank Shot **and** a  Point Blank Shot FEAT. 

Even if you have PBS and another feat in the PBS skill chain, it can not be selected.

**Comment by LegacyKing** [comment]
That's because the feat isn't Point Blank Shot, it's supposed to be Point-Blank Shot. One is the text version, and the other is the actual requirement, which is missing a hyphen.

**Comment by LegacyKing** [comment]
DATA-3225
PF - Typographical Error when referencing Point-Blank Shot (not Point Blank Shot)

**Comment by LegacyKing** [comment]
Fixed.

**Comment by nuwar** [comment]
Thanks.
