### ISSUE TITLE
Getting to many feat choices at level one when using Unchained book and an Archetype.

### ISSUE THREAD

**Issue by grickaby** [PCGen/pcgen#2831]
If you create a Monk, then under Class Features Tab, select Unchained Monk from Monk Class Selection; and then you select an Archetype from the respective Tab, it gives you at level one the ability to select 2 feats from Unchained Monk, 2 feats from Zen Archer, and 2 feats for being a level 1 human.

![screen-cap](https://cloud.githubusercontent.com/assets/1483161/25875699/82060850-34de-11e7-9187-155dc4eb757f.png)

**Comment by LegacyKing** [comment]
Send a pcg file to help@pcgen.org - or drop the file here: https://pcgenorg.atlassian.net/browse/DATA-3261

**Comment by grickaby** [comment]
https://pcgenorg.atlassian.net/browse/DATA-3261

I couldn't add it to he issue on jira, so here is the pcg file.



*_________________________Geoffrey Rickaby*
grickaby@gmail.com
*C:* (414) 336-5916

**Comment by LegacyKing** [comment]
I running the latest dev build, and not seeing the two Zen Feats. I suspect this was already fixed in the following months since 6.07.01 was released.

![image](https://cloud.githubusercontent.com/assets/2759875/26757998/33d6639a-4885-11e7-8570-d553008d901e.png)

**Comment by grickaby** [comment]
This is what i am seeing on my end, and i am using 6.07.01.



*_________________________Geoffrey Rickaby*
grickaby@gmail.com

**Comment by grickaby** [comment]
I guess the issue is if you set a monk as unchained, you should not be able
to select an Archetype as well.



*_________________________Geoffrey Rickaby*
grickaby@gmail.com

**Comment by LegacyKing** [comment]
6.07.01 doesn't incorporate the changes that should have prevented certain Monk Archetypes from being taken. I'll try to get 6.07.02 released tonight. We've been forcing some fixes through.
