### ISSUE TITLE
PCGen Linux release 6.06.01

### ISSUE THREAD

**Issue by Xeddius** [PCGen/pcgen#2861]
The pcgen.sh file contains dos line endings and fails to launch.

**Workaround/Fix:**
run dos2unix from the unzipped folder.

**example:**
```bash
dos2unix pcgen.sh 
````

**Comment by javydreamercsw** [comment]
This is part of a bigger change on pull request #2381.

I suggest closing this issue @LegacyKing.

**Comment by LegacyKing** [comment]
Grab 6.07.02 and see if that worked.
