### ISSUE TITLE
SRD 5 - Shouldn't be able to multiclass into monk with DEX < 13

### ISSUE THREAD

**Issue by ogregoire** [PCGen/pcgen#2868]
Currently, in PCGen it's possible to multiclass into monk with DEX less than 13. The [SRD 5.1](http://dnd.wizards.com/articles/features/systems-reference-document-srd) (page 56) says it's impossible.

Case:

Create a new non-Monk character with SRD 5 rules. Make sure it has Wisdom above 13 and Dexterity less than 13. Try level up as Monk. You end up level 2 without any trouble.

Expected:

Selecting Monk as new class should not be possible, because the Dexterity is lower than 13.

**Comment by LegacyKing** [comment]
(Facepalm) Totally missed this report here... Ah well, we can get it in the 6.07.03 release...

**Comment by LegacyKing** [comment]
`CATEGORY=Internal|Multiclass Allowed.MOD	ABILITY:Internal|AUTOMATIC|Multiclass Allowed ~ Monk|PRESTAT:2,WIS=13,DEX=13
`

**Comment by LegacyKing** [comment]
https://github.com/PCGen/pcgen/pull/2907
