### ISSUE TITLE
Elder Dwarf still has Hardy as his racial trait

### ISSUE THREAD

**Issue by Harmitage** [PCGen/pcgen#2912]
I'm not sure if it is possible for multiple selection traits, so I'm willing to find out. 

When you select Elder Dwarf subrace, Hatred is automatically switched to Ancient Enmity, Greed is replaced with Lorekeeper, and you can replace Hardy with either magic resistant or stubborn. But there is no tip that you should replace Hardy. Is this okay or is there any way to do this kind of thing?

**Comment by LegacyKing** [comment]
There is no easy method to flag that.

**Comment by LegacyKing** [comment]
I could force a choice, but *shrug* not sure if it is worth the effort.

**Comment by LegacyKing** [comment]
Fixed: https://github.com/PCGen/pcgen/pull/3406
