### ISSUE TITLE
pcgen60702_win_install.exe lacks of pcgen.exe

### ISSUE THREAD

**Issue by ksingvo** [PCGen/pcgen#2934]
There is no pcgen.exe in pcgen60702_win_install.exe. 
The Desktop icon references to it and program start fails therefore.

As the Sourceforge download was much faster than github, I tested SF archive only (yet).

Best regards,
Klaus.

**Comment by LegacyKing** [comment]
Will be fixed in the 6.07.03 release. Thanks!
