### ISSUE TITLE
GMGen lacks Character Sheet, encounters don't work

### ISSUE THREAD

**Issue by Lathelus** [PCGen/pcgen#2935]
Hello! In GMGen there is no Character Sheet tab. Also, adding monsters to combat does not work, messes with attributes and other properties of creatures. Experience awards does not work either, CR isn't recognized and the total exp always shows 0.

**Comment by LegacyKing** [comment]
GMGen has not gotten much love in many years. It well overdue for an overhaul and mass repair, but PCGen requires a Lot of maintenance and attention to bring it into the modern era. I can ask one of the coders to investigate, but I doubt I'll have an answer soon. @grimreaper -- take a look at this request please.

**Comment by LegacyKing** [comment]
@thpr @mertonmonk what should we do with GMGen - sounds like more and more issues. Should we disable it for releases until we can have someone look at it?

**Comment by jigokusaru** [comment]
I know a small bit of Java, would I be able to get the Plugin codes or GMGen codes or both to look at and edit, I can use a Zip copy of PCGen to test things and make a reset if any errors occur.

**Comment by LegacyKing** [comment]
Hi, the code is freely available right here in the repo @jigokusaru  Feel free to download, fork/clone, or whatever works best for you.

**Comment by jigokusaru** [comment]
If i open it with Eclipse to edit, do i need any special library or extra information to make the code "work as is"

**Comment by bruceburge** [comment]
@jigokusaru This should provide you with the details you need, assuming this is up to date 
http://wiki.pcgen.org/Building_PCGen

**Comment by grimreaper** [comment]
I need more specific details or this has since been fixed. I also personally fixed CR showing on the character sheets. Let us know if there something more actionable.
