### ISSUE TITLE
Ability Score Spin Boxes

### ISSUE THREAD

**Issue by kheinzelmann** [PCGen/pcgen#2963]
There appears to have been a regression in the Ability Score Spin Boxes. This is on a 4K monitor, it makes it a little hard to read and edit the values.

This is a nightly build from about a month ago.
![stats_6 07 02](https://user-images.githubusercontent.com/25755189/27572025-5ab9920c-5abe-11e7-87da-abe18f07b611.PNG)

This is the master rolled back enough to allow opening a character sheet.
![stats_6 07 03](https://user-images.githubusercontent.com/25755189/27572024-5ab8a072-5abe-11e7-9dfd-cb8e357e0091.PNG)

**Comment by kheinzelmann** [comment]
So this appears to happen anyplace there is a spin box in a list. The skills tab and the dialog box that pops up after adding a class level both exhibit this issue.

**Comment by LegacyKing** [comment]
@grimreaper @grebenyukaa

**Comment by grimreaper** [comment]
#2982

I'm not opposed to re-introducing those other changes, but more work is needed.
