### ISSUE TITLE
Pathfinder Season 8 needed

### ISSUE THREAD

**Issue by grickaby** [PCGen/pcgen#3073]
Majority of the data for [Pathfinder Season 8](http://paizo.com/pathfinder/pathfinderSociety/pfsrpg/scenarios/season8) isn't listed. You do have 8-1 and 8-5 scenarios.

![image](https://user-images.githubusercontent.com/1483161/28243510-5e980d58-6992-11e7-88ac-211c3c1893c2.png)

**Comment by LegacyKing** [comment]
We lack the volunteer that was doing those up.  Data is only added when a person volunteers their time to add those. If you want to learn how to do whatever scenario you need, reach out to help@pcgen.org.

Cheers,

**Comment by LegacyKing** [comment]
@mjmeans - you able to tackle these any longer?

**Comment by grickaby** [comment]
I'm interested in learning how to do it, however i cannot afford to buy all the books.

**Comment by mjmeans** [comment]
Yes. I have season 8 sheets. I’m just reticent on starting these since there has been so few successful auto builds. I had intended to work on season 8 after I saw a month or so of stable auto builds so that there is little or no chance that any issues that come up in my data entry or testing could be code.. i.e. I want any errors that come up during data entry to be expected to be issues with my data so that I’m not wasting time tilting at windmills.

**Comment by LegacyKing** [comment]
The autobuild system is down for the time being, but we're still adding and releasing items. I wouldn't let the autobuild system bother you. Travis catches many issues up front.

**Comment by LegacyKing** [comment]
@mjmeans did your PR cover all of this?

**Comment by mjmeans** [comment]
No. That's still coming. Not all of season 7 was in. There are 30 scenarios or so per season, I have sheets for all of season 7 and part of season 8 (up to #8-08). I have already entered about half of season 7 and will submit a PR as soon as that is done. And I'll then submit a smaller PR for the portion of season 8 that I have access to.

**Comment by LegacyKing** [comment]
Any update on this @mjmeans ?

**Comment by mjmeans** [comment]
I only have up to season 8 #8. Paizo doesn't provide them. There are only a few ways I can get them: 1) If I play the specific PFS scenarios hosted by another PFS GM who has bought the module; 2) If I buy the module (I'm not willing to spend $300 a year on modules); 3) If some other PFS player that has played or GM'd the module sends their chronicle sheet to me. If the OP wants me to add the season 8 scenarios he needs for his character, he will need to send a copy of his chronicle sheet.

**Comment by grickaby** [comment]
You can contact a regional coordinator
<http://paizo.com/paizo/organizedplay/coordinators> or Tonya Woldridge
<http://paizo.com/people/TonyaWoldridge> who is the Paizo community
manager. If you explain that you are contributing to PCGen, they may
provide what you need. Pathfinder Society is currently in the middle of
Season Nine. I can provide chronicle sheets for Paizo's Starfinder, i am
GMing those right now, just not Pathfinder.



*_________________________Geoffrey Rickaby*
grickaby@gmail.com
*C:* (414) 336-5916

**Comment by LegacyKing** [comment]
@grickaby I can show you how we set up the system for PFS, and can do the same for Starfinder, but I don't play in Society games and don't have the materials, so another volunteer would have to take this on. If you're willing, I'll dedicate the time to help you set this up.

**Comment by mjmeans** [comment]
I had contacted Paizo directly. The scenario chronicle sheets for any scenario that they charge for will not be provide to me by them. They clearly don't want them in any searchable database and their aren't covered by OGL. They can be received only by purchasing the scenario or by being given one for playing a game. After that, what happens to the chronicle sheet, including adding them into PCGen is tentatively okay , but they are leery. I believe the fact that I have gone to great lengths to make them usable in PCGen without allowing them to be easily searched within the program is the only reason they are currently allowed. So, as I said above, either I have to have purchased or played the scenario personally, or someone who has purchased or played the scenario has to send me a copy of the chronicle sheet for me to be able to add it in. And then it will be in PCGen in the next release.

IMPORTANT: Don't attach any chronicle sheets here or put them on any public download, or they will surely cry foul and withdraw permission.

If you want to contribute a chronicle sheet you played or a chronicle sheet form a scenario you purchased, you will have to make a PDF of **ONLY** the chronicle sheet. Then contact LegacyKing on the PCGen-experimental email list for my direct contact information. (I don't think it's possible to send private messages in GitHub).

**IMPORTANT**: I can't stress this enough. If someone sends me an entire scenario that I don't have a license to, I will immediately delete it and the chronicle sheet will not be processed for future inclusion in PCGen. I can't risk even the appearance of violating Paizo's copyrights. Don't attach any chronicle sheets here or put them on any public forum or download, or they will surely cry foul and withdraw permission.

**Comment by xenusuk1** [comment]
Happy to add sheets I have access to once the PR for part of 8 is done.

**Comment by mjmeans** [comment]
Chronicle sheets don't have to be added in order. If you have any season 8 or 9 chronicle sheets you want added to PCGen, you can send them to me and I'll add them to PCGen usually within a few weeks (sometimes within a few days), depending on my schedule. It will be in the next release of PCGen and you can get early access by downloading the GitHub repo. and copying the chronicle sheets folder tree into a recent copy of PCGen.

**Comment by xenusuk1** [comment]
items and abilities from the sheets are missing in season 7 pcgen files at the moment.  Can send copies of s7 sheets I have if you need them.  s7_abilities only contains 7-01 and 7-02.

**Comment by mjmeans** [comment]
Sorry. I had created a branch to put in s7 3-20 in august but a few weeks later after I tested it, it had conflicts with the main branch and I see now that I never resolved those and completed the pr. I just learned about git cherry-pick and I'm trying that to see if that is able to move those changes into a new branch from current master.

**Comment by mjmeans** [comment]
I submitted the PR for S7 up to s7-20. I have the rest of S7 to do and I also have S8-00 to S8-08. If you have any chronicles after S8-08 please upload them [here](https://1drv.ms/f/s!An5FXC0CDJ4nsexj-fOwstKCe5TOaw). In order to try to protect he integrity of the data, this link will be available for 1 week only.

**Comment by xenusuk1** [comment]
got a few and 7-98

**Comment by mjmeans** [comment]
I already have 7-01 to 7-29 & 7-98 & 7-99. Plus 8-00 to 8-08. I will be working on the rest of 7 tis weekend.

**Comment by xenusuk1** [comment]
ok, that seems to have worked.

**Comment by YogoZuno** [comment]
I have access to all PFS and SFS scenarios. If you message me, I may be able to provide a way for you to get access to the data you need.

**Comment by mjmeans** [comment]
I'm on vacation. I'll be back next week. I'll try to touch base then. FYI, there is no way to PM on GitHub. Try sending a message to the PCGen yahoo group email for drew to forward your email address to me. I can then contact you directly and make arrangements. The only other way is to use a temporary one drive link like I did last month.

**Comment by mjmeans** [comment]
Most of season 8 has now been completed and submitted as a PR as well as missing items and fixes to season 7. I'm still missing the following chronicle sheets for season 8: 10, 13, 14, 15, 16, 17, 22, 24, 25, 99B, and 99C. So I can't add those until I actually play or run those scenarios or someone else who has done so sends me a copy of their chronicle sheet. I prefer a PDF of the actual chronicle sheet since then it's just copy-paste. I only have about 4 season 9's and none of them are in PCGen yet. Season 9 ends in a little over a month so I'll need to get the collection somehow.

**Comment by YogoZuno** [comment]
I have a drop box that contains legal copies all of the season 8 and 9
scenarios to date, including all those missing ones you list. I can share
these, but I don't wish to post it publicly (the files are water marked,
and not for public distribution). If there is some way I can privately
share links with you,I am happy to do so.

Alternatively,I can try pulling out just the chronicle sheets, but I
suspect that will take a good deal of time on my part (even if it is
doable), and I'd like to avoid this option if I can.

Michael Clarke

**Comment by LegacyKing** [comment]
Send the information to HELP@PCGEN.org, or send me your contact and I'll hook you up offline to Mark.

**Comment by LegacyKing** [comment]
Season 8 added.
