### ISSUE TITLE
Pathfinder Inner Sea Magic source missing a class

### ISSUE THREAD

**Issue by adamjorr** [PCGen/pcgen#3250]
This sorcerer archetype is missing from the Inner Sea Magic source:

http://www.d20pfsrd.com/classes/core-classes/sorcerer/archetypes/paizo-sorcerer-archetypes/razmiran-priest/

**Comment by evilpixie87** [comment]
The Razmiran Priest shows up just fine. Perhaps you're looking for "False Priest". d20pfsrd.com isn't allowed to use product identity names, like Razmiran, so they often are forced to slightly alter the name. But trust me, it's the same archetype!

**Comment by adamjorr** [comment]
Oh, duh. Thanks!
