### ISSUE TITLE
Shackles Seafarer trait is bugged

### ISSUE THREAD

**Issue by allpossibledogs** [PCGen/pcgen#3348]
Currently this trait cannot be taken by characters with their Region of Origin set to Shackles because the trait appears to have been coded incorrectly, bug shown in screenshots http://i.imgur.com/ChKlfLr.png http://i.imgur.com/OOVQvs9.png http://i.imgur.com/ub1cq5Q.png

**Comment by LegacyKing** [comment]
@evilpixie87 did you already fix this?

**Comment by evilpixie87** [comment]
I know nothing about this. Never knew it existed. 

    On Sunday, August 20, 2017 9:55 PM, Andrew Maitland <notifications@github.com> wrote:
 

 @evilpixie87 did you already fix this?—

**Comment by evilpixie87** [comment]
PR submitted
