### ISSUE TITLE
Paizo Starfinder

### ISSUE THREAD

**Issue by grickaby** [PCGen/pcgen#3366]
Any plans on adding Paizo's new system Starfinder to PCGen?

**Comment by LegacyKing** [comment]
You mean like this Starfinder stuff?

`Android	SORTKEY:A_PlayableRace	SIZE:M	SOURCEPAGE:p.42	RACETYPE:Humanoid	TYPE:Humanoid	RACESUBTYPE:Android	MOVE:Walk,0	LEGS:2	HANDS:2	STARTFEATS:1	BONUS:STAT|DEX,INT|2	BONUS:STAT|CHA|-1			ABILITY:Race|AUTOMATIC|Android`

`Human		SORTKEY:A_PlayableRace	SIZE:M	SOURCEPAGE:p.44	RACETYPE:Humanoid	TYPE:Humanoid	RACESUBTYPE:Human		MOVE:Walk,0	LEGS:2	HANDS:2	STARTFEATS:1										ABILITY:Race|AUTOMATIC|Human	XTRASKILLPTSPERLVL:SkillPointBonus`

`Kasatha	SORTKEY:A_PlayableRace	SIZE:M	SOURCEPAGE:p.46	RACETYPE:Humanoid	TYPE:Humanoid	RACESUBTYPE:Kasatha	MOVE:Walk,0	LEGS:2	HANDS:4	STARTFEATS:1	BONUS:STAT|STR|2	BONUS:STAT|INT|-2	BONUS:STAT|WIS|2	ABILITY:Race|AUTOMATIC|Kasatha`

`Lashunta	SORTKEY:A_PlayableRace	SIZE:M	SOURCEPAGE:p.48	RACETYPE:Humanoid	TYPE:Humanoid	RACESUBTYPE:Lashunta	MOVE:Walk,0	LEGS:2	HANDS:2	STARTFEATS:1	BONUS:STAT|CHA|2							ABILITY:Race|AUTOMATIC|Lashunta`

`Shirren	SORTKEY:A_PlayableRace	SIZE:M	SOURCEPAGE:p.50	RACETYPE:Humanoid	TYPE:Humanoid	RACESUBTYPE:Shirren	MOVE:Walk,0	LEGS:2	HANDS:2	STARTFEATS:1	BONUS:STAT|CON|2	BONUS:STAT|WIS|2	BONUS:STAT|CHA|-2	ABILITY:Race|AUTOMATIC|Shirren`

`Vesk		SORTKEY:A_PlayableRace	SIZE:M	SOURCEPAGE:p.52	RACETYPE:Humanoid	TYPE:Humanoid	RACESUBTYPE:Vesk		MOVE:Walk,0	LEGS:2	HANDS:2	STARTFEATS:1	BONUS:STAT|STR|2	BONUS:STAT|INT|-2	BONUS:STAT|CON|2	ABILITY:Race|AUTOMATIC|Vesk`

`Ysoki		SORTKEY:A_PlayableRace	SIZE:M	SOURCEPAGE:p.54	RACETYPE:Humanoid	TYPE:Humanoid	RACESUBTYPE:Ysoki		MOVE:Walk,0	LEGS:2	HANDS:2	STARTFEATS:1	BONUS:STAT|STR|-2	BONUS:STAT|INT|2	BONUS:STAT|DEX|2	ABILITY:Race|AUTOMATIC|Ysoki`

**Comment by grickaby** [comment]
Yep. I was looking through the data to see if it was being worked on, i didn't see it.

**Comment by LegacyKing** [comment]
That's because it's hiding on my computer as I work on it. Creating a new game system, outputsheet support, and data files takes some time. And you're probably looking in the wrong spot. Starfinder will appear in the Newsource section before it debuts on the main repo...

**Comment by LegacyKing** [comment]
Skills are already posted.

**Comment by grickaby** [comment]
That would be why. Thank you for putting in the effort either way. If you need help writing stuff, i can pitch in some time.

**Comment by LegacyKing** [comment]
Jump on our live chat system, and I'll put you to work. :)  

https://www.hipchat.com/gz9QBLp23
