### ISSUE TITLE
False positive error (tab lines catched)

### ISSUE THREAD

**Issue by odraccir** [PCGen/pcgen#3369]
https://github.com/PCGen/pcgen/blob/6942d141b082cb202256df4d7f753527402c31c3/code/src/java/pcgen/persistence/lst/PCClassLoader.java#L254

in a class.lst, when modding a class adding only new prerequisite, without including any level line after the mod (but a line full of tab or, probably, not tested, an empty line) this report an error:
11:39:08.883 SEVERE Thread-10 PCClassLoader:259 Expected a level value, but got '' instead (as a level line in Bard) in source file:/E:/pcgen/vendor/Gozzilioni/supplement/UnearthedArcana/ua_classes.lst
11:39:08.883 SEVERE Thread-10 PCClassLoader:263   Rest of line was: 														

an example from my repo: 

https://github.com/odraccir/pcgen/blob/ff08be0f5741e1bb7c4ded0340bfcadb6b52865a/vendor/Gozzilioni/supplement/UnearthedArcana/ua_classes.lst#L154

**Comment by LegacyKing** [comment]
PRECLASS:1,x=y is the typical format for the PRExxx.

@grimreaper you able to look into the report?

**Comment by odraccir** [comment]
@LegacyKing in the meantime that @grimreaper checks, i will try to change the preclass to the typical format and see if the error persists.

**Comment by odraccir** [comment]
modified:
https://github.com/odraccir/pcgen/blob/382ea1f1bac997b2ef9fd8002a7b8b04cd0ea647/vendor/Gozzilioni/supplement/UnearthedArcana/ua_classes.lst#L154

but the error persists:
12:56:38.969 SEVERE Thread-6 PCClassLoader:259 Expected a level value, but got '' instead (as a level line in Bard) in source file:/E:/pcgen/vendor/Gozzilioni/supplement/UnearthedArcana/ua_classes.lst
12:56:38.969 SEVERE Thread-6 PCClassLoader:263   Rest of line was:

**Comment by LegacyKing** [comment]
Can you submit a proper PR for the issue?

**Comment by odraccir** [comment]
Jira created [CODE-3204](https://pcgenorg.atlassian.net/browse/CODE-3204)

**Comment by LegacyKing** [comment]
Okay, still waiting on @grimreaper since he's the only code monkey I've seen around in awhile.
