### ISSUE TITLE
Pathfinder - Zen Archer Archetype too many feats issue

### ISSUE THREAD

**Issue by grickaby** [PCGen/pcgen#3371]
I am getting a too many feats notice for a Zen Archer archetype. I checked versions 6.7.2 and 6.7.3 and it is occurring in both releases.

![2](https://user-images.githubusercontent.com/1483161/29738415-a1dbcd78-89e7-11e7-85cb-f870969bfc65.png)
![1](https://user-images.githubusercontent.com/1483161/29738414-a1cb7770-89e7-11e7-8511-3af60a76f853.png)

**Comment by LegacyKing** [comment]
Looks like the pool got removed. Have you taken any Archetype or removed the Zen Archetype since?

**Comment by grickaby** [comment]
i tried to create a new character and it did the same thing.

**Comment by LegacyKing** [comment]
Fixed: https://pcgenorg.atlassian.net/browse/DATA-3361
