### ISSUE TITLE
Starfinder Resolve Points not correct

### ISSUE THREAD

**Issue by jimmifett** [PCGen/pcgen#3419]
Resolve Points not calculating properly. Should be 1/2 Char Level (min 1) plus class ability mod.

In this instance, should be 4, but showing 3.
[Mohati Shyrenku.zip](https://github.com/PCGen/pcgen/files/1315352/Mohati.Shyrenku.zip)

**Comment by LegacyKing** [comment]
Fixed... will be in the next release.
