### ISSUE TITLE
Starfinder Soldier Key Ability

### ISSUE THREAD

**Issue by Hectate** [PCGen/pcgen#3449]
In Starfinder, Soldiers get to pick either Strength or Dexterity, but the 'Feats and Abilities' page's 'Soldier's Key Ability' has a 'Total' of 2 instead of 1. This means you have to select both of them to make PCGen happy that your selections are complete.

**Comment by Hectate** [comment]
I just realized that this is a sources issue and there are separate repositories for that sort of thing. Let me know if you'd rather me move to that and open a separate issue.

**Comment by LegacyKing** [comment]
Fixed
