### ISSUE TITLE
Starfinder: Shirren host gender missing

### ISSUE THREAD

**Issue by tsacks** [PCGen/pcgen#3450]
Shirren have three sexes in game: Male, Female, and Host. Host is not an available option.

At the moment, can use Neuter/Unknown as a placeholder.

I was looking into how to submit the fix, but I've always been a bit bad with the LST format.

**Comment by LegacyKing** [comment]
LST isn't responsible for gender/sex, that's hardcoded java.

**Comment by LegacyKing** [comment]
@grimreaper are you able to tackle this?

**Comment by LegacyKing** [comment]
https://github.com/PCGen/pcgen/pull/3466
