### ISSUE TITLE
Pathfinder: 'Masterwork' is missing in Item Customier

### ISSUE THREAD

**Issue by simiczhang** [PCGen/pcgen#3483]
Step: 
1. File -> New
2. Inventory -> Purchase
3. Search 'Longsword' and choose Longsword
4. Click 'Add Custom'

Expected:  'Masterwork' is in modifier list
Actual: 'Masterwork' is NOT in modifier list

Cause: recent commit https://github.com/PCGen/pcgen/commit/d3426d3e53a144117519cdca98153fa699958d0f cause this regression

**Comment by LegacyKing** [comment]
https://github.com/PCGen/pcgen/pull/3485
