### ISSUE TITLE
Not able to add energy resitance in race builder

### ISSUE THREAD

**Issue by RexxarOgre** [PCGen/pcgen#3509]
In race builder can add outsider (Native) under race type but doesn't allow you to pick what plane it's from have anywhere so cannot add energy resistance have downloaded and changed to any version I can find still not able to add it

**Comment by LegacyKing** [comment]
Just to give an FYI - The monkeys that fix bugs all check the JIRA system over at pcgenorg.atlassian.net. Listing it here, well, it will get noticed eventually, but a few days can make the difference between being in the most recent release, or not.  Anyways, add plane and resistance choices - check!

**Comment by evilpixie87** [comment]
JIRA created - DATA-3504

**Comment by evilpixie87** [comment]
PR sent - Close issue
