### ISSUE TITLE
pcgen.org - server not found

### ISSUE THREAD

**Issue by robertkosten** [PCGen/pcgen#3522]
Hi, looks like there is currently no DNS information published (the domain is still registered though).

**Comment by karianna** [comment]
Yes, Anestis has fired off a DNS propagation refresh request, but it's still bouncing around.  Can you check in 24 hours and let us know if you're back up?

Also paging @thpr as there's a separate librepo issue.

**Comment by robertkosten** [comment]
Hi, I tried again, still no luck on google DNS, 8.8.8.8 (my default), but I also tried a few others, e.g. 9.9.9.9 (City of London Police) & 80.80.80.80 (Freenom), both of which return an ip (114.31.74.56) by now.

**Comment by karianna** [comment]
Same here - this is very odd.  I think Google is blocking that entry for some reason (possibly thinks it's dangerous or bad somehow).

**Comment by robertkosten** [comment]
Let's say: it makes me rethink my choice of not running my own djbdns until now...

**Comment by robertkosten** [comment]
Looks like google has finally relented. I'd say the issue can be closed, as far as I'm concerned :-)

**Comment by karianna** [comment]
Yes it's resolved although we still need to fix ci.pcgen.org and the build
