### ISSUE TITLE
Animal Focus doesn't scale by Hunter level for companions

### ISSUE THREAD

**Issue by craig-sanders** [PCGen/pcgen#3541]
I just levelled up a Hunter to 8th level in pcgen and noticed that while the bonus from Animal Focus is correctly applied to the Hunter (e.g. an extra +2 ability enhancement for Bull, Bear, Eagle, Tiger at 8th, and another +2 at 15th), it is not applied correctly to the Animal Companion.  The AC gets only the basic enhancement, without the increases at 8th & 15th level.

This seems to be because the higher-level extra bonuses are tied to HunterAnimalFocusLVL, and an Animal Companion doesn't have one.

e.g. for Bear:

```
Bear
    KEY:Hunter Animal Focus ~ Bear
    CATEGORY:Special Ability
    TYPE:HunterAnimalFocusAbility
    VISIBLE:DISPLAY
    DEFINE:HunterAnimalFocusBearBonus|0
    DESC:Get +%1 enhancement bonus to constitution|HunterAnimalFocusBearBonus
    BONUS:STAT|CON|HunterAnimalFocusBearBonus|TYPE=Enhancement
    BONUS:VAR|HunterAnimalFocusBearBonus|2
    BONUS:VAR|HunterAnimalFocusBearBonus|2|PREVARGTEQ:HunterAnimalFocusLVL,8
    BONUS:VAR|HunterAnimalFocusBearBonus|2|PREVARGTEQ:HunterAnimalFocusLVL,15
    SOURCEPAGE:p.27
```

and Bat (where the bonuses are longer range darkvision and blindsight rather than more ability enhancement):

```
Bat
    KEY:Hunter Animal Focus ~ Bat
    CATEGORY:Special Ability
    TYPE:HunterAnimalFocusAbility
    VISIBLE:DISPLAY
    DEFINE:HunterAnimalFocusBatSight|0
    DESC:Get darkvision to range %1 feet|HunterAnimalFocusBatSight
    DESC:and blindsense to 10 feet|PREVARGTEQ:HunterAnimalFocusLVL,15
    ABILITY:Special Ability|AUTOMATIC|Blindsense|PREVARGTEQ:HunterAnimalFocusLVL,15
    ABILITY:Special Ability|AUTOMATIC|Darkvision
    BONUS:VAR|HunterAnimalFocusBatSight|60
    BONUS:VAR|HunterAnimalFocusBatSight|30|PREVARGTEQ:HunterAnimalFocusLVL,8
    BONUS:VAR|DarkvisionRange|HunterAnimalFocusBatSight|TYPE=Base
    BONUS:VAR|BlindsenseRange|10|TYPE=Base
    SOURCEPAGE:p.27

```

Probably the best/easiest fix is to add and update HunterAnimalFocusLVL to the companion itself - but that's just a guess (I'm not familiar with the code, nor am I an expert in pcgen variables or .pcg files)

Or maybe just add a condition that expresses  "**or** CLASS=Companion **and** LEVEL=x)".  Unfortunately (see http://www.d20pfsrd.com/classes/core-classes/druid/animal-companions/) Animal Companion levels don't exactly match Hunter Class Levels: 

The AC is HD 7 when the Hunter is Lvl 8.   They are HD 12 when the Hunter is Lvl 14 and remain at HD 12 when the Hunter is Lvl 15.    Maybe HD and Natural Armor Bonus together could be used as a proxy for HunterAnimalFocusLVL...on second thoughts, that won't work because the AC may have the _Improved Natural Armor_ feat or similar.

**Comment by LegacyKing** [comment]
There is a way, but the vars don't cross-over as you'd expect. I won't have time to look till the weekend.

**Comment by LegacyKing** [comment]
Please open a jira data bug - pcgenorg.atlassian.net

**Comment by evilpixie87** [comment]
JIRA created - DATA-3503

**Comment by evilpixie87** [comment]
PR sent. Close issue
