### ISSUE TITLE
Pathfinder Slayer Vanguard Tactician ability grants all teamwork feats instead of one

### ISSUE THREAD

**Issue by MarauderIIC** [PCGen/pcgen#3544]
In Pathfinder's Slayer Vanguard archetype, the Tactician ability adds all teamwork feats to the character instead of allowing for the selection of a single teamwork feat.

Tactician (Ex): At 2nd level, a vanguard receives a teamwork feat as a bonus feat. He must meet the prerequisites for this feat. Once per day as a standard action, the vanguard can grant one of his teamwork feats to all allies within 30 feet who can see and hear him. Allies retain the use of this bonus feat for 3 rounds plus 1 round for every 2 levels the vanguard possesses. Allies do not need to meet the prerequisites of this bonus feat. Whenever the vanguard is able to select a new slayer talent, he can instead choose to gain an additional use per day of this ability. This ability replaces the slayer talent gained at 2nd level.

**Comment by MarauderIIC** [comment]
This should fix it, and Slayer Vanguard Lookout not adding one to initiative either.

[acg_abilities_class.lst.txt](https://github.com/PCGen/pcgen/files/1544373/acg_abilities_class.lst.txt)

**Comment by LegacyKing** [comment]
Please open a jira Data Bug ticket - pcgenorg.atlassian.net

**Comment by evilpixie87** [comment]
JIRA created - DATA-3502

**Comment by evilpixie87** [comment]
PR sent - close issue
