### ISSUE TITLE
Adding ranks to Fly cannot be undone via UI

### ISSUE THREAD

**Issue by kalexmills** [PCGen/pcgen#3571]
Running 6.06.01 on Windows 10

Adding ranks to Fly via the UI to a Human Aristocrat. It does not seem that the ranks, once added, can be removed.

The "down arrow" is unresponsive.

Has this been fixed on master? If so, reply with the commit and I'll be happy to attempt a backport.

**Comment by LegacyKing** [comment]
Use 6.07.05
