### ISSUE TITLE
pcgen with mysql database

### ISSUE THREAD

**Issue by nevarim** [PCGen/pcgen#3584]
hi

i'm trying in any part of your program if there is a way to make it working with mysql database, you knoww if it works without lst files ?

thanks
Neva

**Comment by LegacyKing** [comment]
Not to my knowledge. LST is specific to different file types. I don't see any easy transition to any database.

**Comment by LegacyKing** [comment]
Discussions surround databases have been brought up. If you have an interest, the code team is available to chat. Most of the current code monkeys are North America time zone, but if you log into our support room, you should be able to connect with one - https://www.hipchat.com/gmddByrFS
