### ISSUE TITLE
Can't build using gradle on linux

### ISSUE THREAD

**Issue by TristenCocking** [PCGen/pcgen#3587]
I am trying to use gradle to build pcgen from the linux terminal. However it is throwing an error returning that it could not find find method compileOnly()
```
FAILURE: Build failed with an exception.

* Where:
Build file '/home/*******/Desktop/build.gradle' line: 170

* What went wrong:
A problem occurred evaluating root project 'pcgen'.
> Could not find method compileOnly() for arguments [{group=org.jetbrains, name=annotations, version=15.0}] on root project 'pcgen'.
```
Looking on the wiki I found out that pcgen was built on java JDK 6.0 and it might be a problem that I am running java openjdk 8?

**Comment by LegacyKing** [comment]
This is the master development from github? Or are you trying to build a much older version of pcgen?

**Comment by TristenCocking** [comment]
The master

**Comment by LegacyKing** [comment]
You can try this: gradle build --project-cache-dir c:\gradle\cache

Just make sure the directory exists.

**Comment by LegacyKing** [comment]
We've been successfully building from the master branch during the last week. If you still have issues, jump on our support group live chat - hang out and please be patient, a volunteer will guide you in the right direction. -- https://www.hipchat.com/gmddByrFS
