### ISSUE TITLE
[SOURCE] [PAIZO] Occult Origins

### ISSUE THREAD

**Issue by Laski** [PCGen/pcgen#3665]
http://paizo.com/products/btpy9grw?Pathfinder-Player-Companion-Occult-Origins

I know this should go on the JIRA, but I'm unable to log in for some reason. If you move it there and close this, thanks!

**Comment by LegacyKing** [comment]
I'm the JIRA Administrator, send me the problem offlist here: help@pcgen.org or you can try to catch me on the support chat line North America evenings UTC -0800 6pm to 10pm https://www.hipchat.com/gmddByrFS

**Comment by Laski** [comment]
The issue with JIRA? It's an Atlassian problem, not yours :smile: 
The issue with PCGEN? This source is not in the program. It made sense to me to open an issue for it after Occult Adventures was implemented (a strict prerequisite for this one).

**Comment by evilpixie87** [comment]
I'll add this to my list of requests. I'll try to get it done for the next release, but no promises.

**Comment by LegacyKing** [comment]
JIRA: https://pcgenorg.atlassian.net/browse/NEWSOURCE-340

Closing this in favor of the JIRA.
