### ISSUE TITLE
Custom content

### ISSUE THREAD

**Issue by dcpc007** [PCGen/pcgen#3666]
Hi,

Back to test this project again :)

Buty, is it possible to make some custom like : 
- implement local rules like remove feat to gain another, or add an extra feat (mmore than normal at a level) ?
- Is it possible to add locally specifi prestige class ? or modifed one (DM sometimes change prerequisites)

**Comment by LegacyKing** [comment]
Within reason, anything is possible. In PCGen, you can easily remove a manually added feat, and replace it with another feat. You can also manually add a point to the FEAT Pool, or you can code in a bonus to grant an extra feat. 

PCGen was designed to be customizable by the end user (you). All the files are flat text files easily opened in any freely available text editor of your choice. We supply documentation about the tags, have a live chat support room where volunteers hang out when available, and tutorial videos on youtube - All links to these options and more can be found at http://pcgen.org

**Comment by dcpc007** [comment]
Thx a lot, i'll try again because start to be hard to manage high level PC with 2 prestige class and some customizations (and the skill part with specific bonuses and not all-cases bonuses start to be really hard).
I hope i'll have not too many code to add.

Current need is 3.5 rogue + dungeon dwelver (adventurer codex) + shadowwalker (DMG).
