### ISSUE TITLE
PCGen API

### ISSUE THREAD

**Issue by Laski** [PCGen/pcgen#3698]
Is there an implemented / in progress / idea of PCGen having an API? I'd love to develop some things on top of PCGen's deep knowledge of the character rules (and obviously contribute them to the community) but
- I don't want to mess with the main code to add stuff unrelated with character generation (I think PCGen is big and good enough as it is)
- I'd prefer not having to read + understand + comprehend the entire architecture just to add unnecessary things
- I don't like Java :sweat_smile:

**Comment by karianna** [comment]
Long term yes, I doubt you'll see anything in the next year though.

**Comment by Laski** [comment]
Well I guess I'll need to get my hands dirty then :sweat_smile: 
Thanks for the quick response!
