### ISSUE TITLE
pcgen.sh uses unix-incompatible linebreak characters

### ISSUE THREAD

**Issue by sarahscheffler** [PCGen/pcgen#3713]
The linebreaks used in pcgen.sh are DOS-style linebreaks (CR+LF).  To use it on Unix you have to convert to Unix-style linebreaks (LF only).  It runs great on Ubuntu and OS X when converted.

I'm happy to make a PR for this, but I wanted to check and make sure this was unintentional first.

**Comment by karianna** [comment]
Yes it should be changed thank you!

**Comment by karianna** [comment]
@sarahscheffler That's a bug indeed, a PR would be welcome!

**Comment by LegacyKing** [comment]
@thpr did a PR regarding this. *Should* be resolved. Closing this...
