### ISSUE TITLE
HP Re-Roll not counted correctly

### ISSUE THREAD

**Issue by WBSpitfire** [PCGen/pcgen#3725]
Version: 6.07.06

When choosing to re-roll HP, Though it is counted in the bottom-right of the summary screen, it is not actually applied to the character stats.

**Comment by LegacyKing** [comment]
@mertonmonk @grimreaper @thpr Can one of you investigate this?

**Comment by grimreaper** [comment]
Is this still an issue?

**Comment by grimreaper** [comment]
I think d3027c13761e059f370afdad4471c9c1beb3abe1 fixed this. If not, let us know.
