### ISSUE TITLE
Bloodrage rounds no longer showing on export sheet

### ISSUE THREAD

**Issue by vizzie-tx** [PCGen/pcgen#3754]
Somewhere during the 6.7.x series, PCGen stopped displaying tick boxes for the number of Bloodrager bloodrage rounds on character output sheets.

**Comment by vizzie-tx** [comment]
More information: Adding a check for BloodrageLVL and parallel set based on BloodrageDuration in base;.xml* and csheet_fantasy_generic_export.xml.ftl seems to work correctly for a normal bloodrager, but not for the Urban Bloodrager archetype. Using the formlua calculator tool, it does not look like BloodrageLVL or BloodrageDuration are getting set at all for the Urban Bloodrager.

**Comment by LegacyKing** [comment]
Can you send the character in question to Help@Pcgen.org please? Thanks.

**Comment by LegacyKing** [comment]
Not able to reproduce. PDF export shows the rounds properly.
