### ISSUE TITLE
Missing openjfx-78-backport dependency in build.gradle

### ISSUE THREAD

**Issue by JoshLikesBeer** [PCGen/pcgen#3761]
Running gradlew from command line causes errors for me because it cannot find javafx.scene.image.ImageView.

I resolved the issue for myself by adding this line to the dependencies section of build.gradle:
compile group: 'net.java.openjfx.backport', name: 'openjfx-78-backport', version: '1.8.0-ea-b96.1

**Comment by karianna** [comment]
We shouldn't need Javafx.... that package was deleted I thought.

**Comment by JoshLikesBeer** [comment]
This class still refers to it:

https://github.com/PCGen/pcgen/blob/master/code/src/java/pcgen/gui2/tools/Icons.java

**Comment by LegacyKing** [comment]
Are you using OpenJDK 8 or standard JDK 8?

**Comment by JoshLikesBeer** [comment]
```
$java -version
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 8.0.5.5 - pxa6480sr5fp5-20171114_01(SR5 FP5))
IBM J9 VM (build 2.9, JRE 1.8.0 Linux amd64-64 Compressed References 20171102_369060 (JIT enabled, AOT enabled)
OpenJ9   - 7ade437
OMR      - 1b656cb
IBM      - 59c3d96)
JCL - 20171113_01 based on Oracle jdk8u151-b12
```

I apparently have the IBM JDK set up as my default for some reason. I set my JAVA_HOME to point to my Oracle JDK and the problem went away.

**Comment by LegacyKing** [comment]
I'm likewise having conflicts with my Java JDK trying to jump to that. @karianna can we eliminate that if we aren't using it?

**Comment by karianna** [comment]
So only Oracle JDK comes with JavaFX bundled, I'll see if I can remove that last dep
