### ISSUE TITLE
Favored class bonus not working for tiefling / Alchemist

### ISSUE THREAD

**Issue by Farawen** [PCGen/pcgen#3830]
Hello,

It seems that the tiefling favored class bonus for alchemist (+1/2 bomb damage) is not working: 
It can be selected but has no effects on bomb damage, even after leveling.

I've attached a simple test (Level 3 alchemist tiefling, Favored class bonus 3*, 12 intelligence). [test1.pcg.gz](https://github.com/PCGen/pcgen/files/1756829/test1.pcg.gz)

Bomb damage should be 2d6 + 2 (+1 because of int, +1 because of fav class bonus = 1/2 * 3), it appears as "1d6+1".

I suspect the wrong number of dice is linked to a different matter (maybe number of dice damage computed at item addition and not re-evaluated). If needed, I'll file another issue after further investigation.

I'm now using pcgen 6.07.06. This behavior was the same with my previous version.

And thanks all for the work!

**Comment by LegacyKing** [comment]
PR submitted. Closing this.
