### ISSUE TITLE
Trait Firebug has no effect

### ISSUE THREAD

**Issue by Farawen** [PCGen/pcgen#3860]
Hello everybody!

The trait _Firebug_ has no effect on an alchemist bombs in the character sheet.

**Expected**: You gain a +1 trait bonus on attack rolls made with thrown splash weapons and alchemist bombs.

**Got**: No change in the character sheet

Trait defined in file:
pathfinder/paizo/player_companion/quests_and_campaigns/qac_abilities.lst  Line 7

The attached file provides an example:
[Firebug.pcg.gz](https://github.com/PCGen/pcgen/files/1781704/Firebug.pcg.gz)
=> Add/remove the firebug trait, no effect on character sheet

Thanks again for the work  (By the way, I was impressed by your reactivity for my last bug report)!

**Comment by evilpixie87** [comment]
The fix is in. Should be added to the next version!
