### ISSUE TITLE
player companion folder structure reverted

### ISSUE THREAD

**Issue by kypvalanx** [PCGen/pcgen#3865]
https://github.com/PCGen/pcgen/commit/5634cab0aef059f74fbaffc55a1abc70250f9c5f

reverted the change that moved player companions into the player companion folder

**Comment by LegacyKing** [comment]
?

**Comment by kypvalanx** [comment]
in resource selection, for the pathfinder game mode, player companions appeared in a player companion subdirectory until this commit.

**Comment by kypvalanx** [comment]
https://github.com/PCGen/pcgen/pull/3869

**Comment by Llisandur** [comment]
Why? None of the other resources are a subfolder of the core rulebooks.

**Comment by kypvalanx** [comment]
there are a lot of books.  it makes it much easier to find the book you're looking for.  i'm in favor of moving the adventure paths, and maybe even the campaign settings into a subfolder as well.

**Comment by Llisandur** [comment]
@LegacyKing Please come weigh in on this.

**Comment by Llisandur** [comment]
My problem with moving all of the player companion and other sections into subcategories of the core rulebooks is that they appear in the middle of the section, rather than at the top. It makes it look really weird and disorganized.

**Comment by kypvalanx** [comment]
could we do something like
paizo
  -core
  -player companions
  -aps

i'm looking at it from the point of view of someone who usually uses a lot of books and it can be slow to find what you want.

**Comment by Llisandur** [comment]
I'm not sure what you're saying in the last one. To me it looks perfect organized as-is, with them all separate folders, but I usually use the search function to find the specific books.
