### ISSUE TITLE
Pathfinder adamantine +1 shield does not have masterwork check penalty reduction

### ISSUE THREAD

**Issue by leftmostcat** [PCGen/pcgen#3887]
Creating a custom "Shield, Heavy Steel" with a +1 enhancement and adamantine material results in a check penalty of -2, the same as the base item. Adamantine implies masterwork, and +1 items must be masterwork. A masterwork shield's check penalty is reduced by 1, so the shield should have a check penalty of -1.

**Comment by LegacyKing** [comment]
Is this the latest version of PCGen?

**Comment by LegacyKing** [comment]
I'm looking at the Core Rulebook, and I don't see how you're even being able to Add Adamantine to a Shield... It's not coded up as a legal selection.

**Comment by leftmostcat** [comment]
This is on v6.07.06 with the "Pathfinder RPG for Players" set of source materials. I choose "Shield, Heavy Steel" on the Purchase screen, click "Add Custom", and "Adamantine" appears in the list of modifiers to the left.

**Comment by LegacyKing** [comment]
While I can see discussions on Adamantine, per the rule book itself, shield is not an option that should be granted. I'll fix the code to not allow Adamantine as a selection for shield.

**Comment by LegacyKing** [comment]
Okay, researched this, and the reason you get Adamantine is if you CHOOSE to use the SHIELD as a Weapon "Shield bash".  Nothing for me to fix, as this is working as intended. The adamantine benefits of a WEAPON are being applied, not armor. 

Cheers,
