### ISSUE TITLE
Graphical bug with UI

### ISSUE THREAD

**Issue by wobbleztheweird** [PCGen/pcgen#3943]
Downloaded program version 6.07.07 this morning, i am aware that it is an unstable version but i read a change log from last September that said this issue was resolved. 

when mousing over various drop menus and typespaces the ui will copy over itself and make the program almost impossible to use, have tried various suggested work arounds to no success

**Comment by LegacyKing** [comment]
Which workarounds have been attempted so we don't duplicate effort?

**Comment by grimreaper** [comment]
I can't replicate this. Going to close this unless we have more specific repro steps.
