### ISSUE TITLE
Pathfinder B5 question

### ISSUE THREAD

**Issue by mjmeans** [PCGen/pcgen#3978]
Concerning B5 that is titles player options only. This doesn't seem typical for recent older bestiary sources. I'm assuming this had to be done to handle some pre-reqs for another new source that had a higher priority. However, I wanted to know if the rest of B5 is planned or is "player options only" going to be the standard from now on; and therefore will apply to B6 and later as well? Or is this a on-off; and what will be the standard policy for new partial sources as we go forward with the new parser (partial sources okay, partial sources okay but discouraged, partial sources rejected except for special cases).

**Comment by LegacyKing** [comment]
The volunteer wanted to get the player options available since Bestiary books take an inordinate amount of time to code.

**Comment by LegacyKing** [comment]
To answer the second part - For source books, I prefer full sources, but since the Bestiaries contain player options (Familiars, Animal Companions, etc.) I will accept a Player's option only version for those only. This is an exception, not a standard.
