### ISSUE TITLE
[Race Builder Design] Race Trait Movement: Flight seems not fully functional.

### ISSUE THREAD

**Issue by Ghostbird** [PCGen/pcgen#3995]
> ### Flight
>
> Type: RacialTrait. BuilderMovementTrait. Advanced  Cost: 0 Description: Fly speed 30' (clumsy); each extra 2 RP spent gives +10 speed and one step maneuverability improvement. [Cost: 4] 

However I cannot find any way in the UI to spend the extra 6 RP points to get it from `Fly speed 30' (clumsy)` to `Fly speed 60' (average)`

**Comment by gameguy95** [comment]
I had trouble with this as well, and I just got around it by making a note to myself about the extra cost and speed, then using the "Flight Manueverabilty" bonus listed in the temporary bonuses section. 
Also, that should be 3 steps above clumsy, which would be good, not average.

**Comment by Ghostbird** [comment]
Ah, thanks for the info. Though Flight Manoeuvrability +3 gives me average, which matches the half-dragon template `fly speed 60 (average)` for this character.

**Comment by LegacyKing** [comment]
Please open a Data Bug on our JIRA --> https://pcgenorg.atlassian.net

One of the volunteers will take a look at it. 

Cheers,

**Comment by LegacyKing** [comment]
https://github.com/PCGen/pcgen/pull/4126 & https://pcgenorg.atlassian.net/browse/DATA-3687
