### ISSUE TITLE
Bug: Inspire Courage temporary condition doesn't add to weapon damage

### ISSUE THREAD

**Issue by Zitchas** [PCGen/pcgen#4062]
Version: v6.07.06

What is expected:
Inspire courage: +1 morale bonus on saving throws against charm and fear effects and a +1 competence bonus on attack and weapon damage rolls, goes up at 5th and every six levels after that.

What happens:
The character receives +1 bonus on attack rolls, but damage roll remains unchanged.

Also tested using the 17th level version that should give a +4 bonus. The +4 is applied to the bonus to hit on the character sheet, but still isn't applied to the damage. (using a generic non-magical warhammer to test)

**Comment by LegacyKing** [comment]
Confirmed...

**Comment by LegacyKing** [comment]
https://github.com/PCGen/pcgen/pull/4125 & https://pcgenorg.atlassian.net/browse/DATA-3686
