### ISSUE TITLE
Bad lvl for discovery axiomatic / anarchic

### ISSUE THREAD

**Issue by Farawen** [PCGen/pcgen#4070]
In pcgen, alchemist discoveries *Anarchic Bombs* and *Axiomatic Bombs* have an alchemist level requirement of 6. The requirement should be of alchemist lvl 8.

Source in pcgen is *Champion of Balance*:
`pathfinder/paizo/player_companion/champions_of_balance/cob_abilities_class.lst`

Source :
[Axiomatic Bombs in d20pfsrd](https://www.d20pfsrd.com/classes/base-classes/alchemist/discoveries/paizo-alchemist-discoveries/axiomatic-bombs/)
[Anarchic Bombs in d20pfsrd](https://www.d20pfsrd.com/classes/base-classes/alchemist/discoveries/paizo-alchemist-discoveries/anarchic-bombs/)

Thank you!

**Comment by LegacyKing** [comment]
FYI - Citation of rules must be sanctioned from original Publisher, in this case Paizo's FAQs or PRD. We love John, but need to validate all thing Paizo from Paizo.

**Comment by Farawen** [comment]
That's quite logical. I could not find it online on PRD but here is a quote from The Book:

From Champions of Balance (ISBN 978-1-60124-603-4, 51299, Paizo ref PZO9443), page 20: 

*Axiomatic Bombs*: When the alchemist creates a bomb, he can choose to have it deal lawful divine damage. Chaotic creatures that take a direct hit from an axiomatic bomb must succeed at a Fortitude save or be staggered on their next turn. Against neutral creatures, axiomatic bombs deal half damage, and such targets are not affected by their staggering effect. Axiomatic bombs have no effect on lawful creatures. **An alchemist must be at least 8th level before selecting this discovery.**

*Anarchic Bombs*: When the alchemist creates a bomb, he can choose to have it deal chaotic divine damage. Lawful creatures that take a direct hit from an anarchic bomb must succeed at a Fortitude save or be staggered on their next turn. Against neutral creatures, anarchic bombs deal half damage, and such targets are not affected by their staggering effect. Anarchic bombs have no effect on chaotic-aligned creatures. **An alchemist must be at least 8th level before selecting this discovery.**

**Comment by LegacyKing** [comment]
https://github.com/PCGen/pcgen/pull/4124 & https://pcgenorg.atlassian.net/browse/DATA-3685
