### ISSUE TITLE
switch from parenthesis to commas

### ISSUE THREAD

**Issue by net-diver** [PCGen/pcgen#4097]
With the switch from parenthesis to commas many of the previously customizable items will now cause 'invalid name' alerts any time you try to create custom items due to commas not being an acceptable character.

So after some researching this is caused by a change to the core rulebook file... and was done 23 days ago... so I am behind things a bit

https://github.com/PCGen/pcgen/blob/master/data/pathfinder/paizo/roleplaying_game/core_rulebook/cr_equip_general.lst

I mostly just stick to tweaking pre-existing files since actual coding is beyond me but I'm a bit confused why the switch to characters that the program itself views as invalid? any information would be appreciated

**Comment by LegacyKing** [comment]
Need a code monkey to answer - @karianna ?

**Comment by karianna** [comment]
https://github.com/PCGen/pcgen/pull/4052 was the PR

**Comment by LegacyKing** [comment]
Yes, but why are commas breaking the customizations? Shouldn't they be using the object KEY? @karianna

**Comment by grimreaper** [comment]
I believe #4042 fixed this. If not ping and we'll re-open.
