### ISSUE TITLE
codacy/checkstyle tab width

### ISSUE THREAD

**Issue by tildar** [PCGen/pcgen#4107]
Checkstyle defaults to 8 wide tabs, but it seems the standard eclipse32_pcgen.xml sets up for 4 wide tabs.

I'm assuming that checkstyle should be adjusted.

I have attempted to modify the checkstyle.xml to count 4 wide tabs, but I'm just not having any luck.

This primarily affects the line length checks, and causes confusion when codacy tags lines as much much longer that what is seen in eclipse.

Maybe someone else will have better luck getting checkstyle set correctly?

**Comment by LegacyKing** [comment]
All files I reviewed have this:

`      <property name="tabWidth" value="4"/>
`
Codacy pulls from the configuration file. Max line length is set to 80. Not sure if that is what you meant.

**Comment by tildar** [comment]
I eventually figured it out. forgot to close this.
