### ISSUE TITLE
Travis-ci is having issues with wget and network failures

### ISSUE THREAD

**Issue by tildar** [PCGen/pcgen#4109]
We seem to have travis fail to build fairly often due to this issue.

I'm trying to find a way to make the wget for dl of zlib128-dll.zip to be more robust, and will try testing changes on my own travis first for now.

If anyone has idea's please speak up.

**Comment by tildar** [comment]
As I work on this, I have been curious what we do with /tmp/zlib.zip after its downloaded?

**Comment by tildar** [comment]
I eventually tracked the jun 26th  failed downloads to some support notices at Sourceforge re: ddos issues, which were fixed later in the day.  I'm still going to keep looking at ways to avoid the build failing out in such cases. Maybe find a second source to dl from if the first fails? -OR- Maybe we don't even need to it to dl, I have not found were it gets used yet.

**Comment by LegacyKing** [comment]
Can we close this issue?  Was this Pull Requested?
