### ISSUE TITLE
Command Plants

### ISSUE THREAD

**Issue by Razytos** [PCGen/pcgen#4110]
Version 6.07.08

"Command Plants" is listed as Lvl 3 Druid Spell, but it is a Lvl 4 for them.

http://paizo.com/pathfinderRPG/prd/coreRulebook/spells/commandPlants.html#command-plants

**Comment by LegacyKing** [comment]
https://pcgenorg.atlassian.net/browse/DATA-3683

**Comment by LegacyKing** [comment]
https://github.com/PCGen/pcgen/pull/4122
