### ISSUE TITLE
Sorcerer Arcane Bloodline

### ISSUE THREAD

**Issue by Razytos** [PCGen/pcgen#4112]
Version 6.07.08

this bloodline is automatically applying the sage archetype "Arcane Bolt" special attack in character sheet even without choosing it.

**Comment by LegacyKing** [comment]
Tested, unable to replicate. 

![image](https://user-images.githubusercontent.com/2759875/42416253-775964fe-821e-11e8-9ff0-230786f5f959.png)

Loading Core Supplements (Which includes Sage Wildblood Archetype in Ultimate Magic)

**Comment by Razytos** [comment]
Hi, i reinstalled the program, created a gnome sorcerer of level 5, selected the standard bloodline "arcane bloodline" and the arcane bolt appeared.

![image](https://user-images.githubusercontent.com/37812242/42418950-828bccb2-82ab-11e8-842e-765b13c92d1d.png)

![image](https://user-images.githubusercontent.com/37812242/42418967-cf7baea2-82ab-11e8-8a6d-91969a49b4ac.png)
