### ISSUE TITLE
Missing Metamagic Rod for Still Spell

### ISSUE THREAD

**Issue by Zitchas** [PCGen/pcgen#4120]
**Version**: v6.07.06
**Datasets loaded:** (tried two different sets)
 **Primary Dataset:** ( Council of Theives Player's Guide, Kingmaker Player's Guide, Guide to the River Kingdoms, Inner Sea Bestiary, Inner Sea Combat, Inner Sea Magic, Inner Sea Races, Inner Sea World Guide, Adventurer's Armory, Adventurer's Armory 2, Dwarves of Golarion, Faiths of Balance, Faiths of Purity, Inner Sea Primer, Advanced Class Guide, Advanced Player's Guide, Advanced Race Guide, Core Rulebook, Ultimate Campaign, Ultimate Combat, Ultimate Equipment, Ultimate Magic

**Alternative Dataset:** Also tested using the provided "Pathfinder RPG Core Supplements" set.

**Environment:** Windows 10 (64bit)

**What was expected:**
 - Metamagic Rod (Still Spell, lesser) should appear in the list of equipment, along with standard and greater variants.

**What occurred:** 
 - The Metamagic Rod (Still Spell, any variant) does not appear in the equipment list.

The first picture shows the purchase list without any filters or search terms, after having expanded "Rod/Metamagic" and scrolled to the spot where "Still Spell" should be.

![rod still spell missing1](https://user-images.githubusercontent.com/32169904/42330527-9a303178-8030-11e8-9c8b-bf2fa4070768.PNG)

The second picture shows the results when searching for "Still Spell," where it shows Distilled Terrap Sap, Elven Still, and Stillgut as the only things available for purchase with the word "still" in it. 

![search equipment for still](https://user-images.githubusercontent.com/32169904/42331505-d0af08f8-8032-11e8-98bb-19d94cdc18be.PNG)

**Comment by Zitchas** [comment]
Just doing some follow up research on this, this rod is listed in the pfsrd at [Metamagic Rod, Still Spell](https://www.d20pfsrd.com/magic-items/rods/metamagic-rods/metamagic-rod-still-spell/).

There it lists the copyright as being attributed to Ultimate Equipment, but perusing my copy of said pdf, I can't find this rod listed in the rod section or in the index.

**Comment by djlimmer** [comment]
There is no still spell rod; the pfsrd is in error.

It would be kind of pointless, because one must use the rod, which
requires a hand, which might as well be used for the somatic components.
DJL


On Thu, Jul 5, 2018, at 10:28 AM, Zitchas wrote:
> Just doing some follow up research on this, this rod is listed in the
> pfsrd at Metamagic Rod, Still Spell[1].> There it lists the copyright as being attributed to Ultimate
> Equipment, but perusing my copy of said pdf, I can't find this rod
> listed in the rod section or in the index.> — You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub[2], or mute the
> thread[3].

Links:

  1. https://www.d20pfsrd.com/magic-items/rods/metamagic-rods/metamagic-rod-still-spell/
  2. https://github.com/PCGen/pcgen/issues/4120#issuecomment-402761382

**Comment by LegacyKing** [comment]
Thanks Doug. Closing this out.
