### ISSUE TITLE
View Character Sheet Error

### ISSUE THREAD

**Issue by demib84** [PCGen/pcgen#4127]
When I buy items with some special materials and magic enhancements, I am getting this error when I go to the character sheet in 6.07.08:

Unable to process sheet
java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Requested ScopeInstance for pcgen.core.EquipmentModifier Special Ability ~ Benevolent ~ Armor and reached a global parent, but have only reached Scope: EQUIPMENT 

Does this with silversheen and Elysium Bronze. Not sure what else will throw that error.

**Comment by LegacyKing** [comment]
@thpr looked and not seeing any Data reason for the error.

@demib84 can you supply a character file that reproduces the error?

**Comment by demib84** [comment]
https://drive.google.com/file/d/1aTVm3OGQ30LDW3n7Q72zflI4o6l6zQ8B/view?usp=sharing

Here is a character with one of the mentioned special material throwing that error for me. I do have a lot of sources (30+ I think) as well. Did a fresh reload to do what mjeans said cleared it and it went just fine. So I guess it is a java. Unfortunately I am not familiar with java at all.

**Comment by LegacyKing** [comment]
Uh, seriously? Do you need all of these sources to build your specific character?

20:34:40.223 INFO Thread-9 SourceFileLoader:567 Loading game Pathfinder_RPG and sources [Pathfinder Society Field Guide, Pathfinder Unchained, Ultimate Magic, Ultimate Equipment, Ultimate Combat, Ultimate Intrigue, Advanced Class Guide, Advanced Player's Guide, Advanced Race Guide, Arcane Anthology, Bestiary, Bestiary 2, Bestiary 3, Occult Adventures, Bestiary 4, Bestiary 5 (Player Options Only), Dark Markets - A Guide to Katapesh (Conversion), Dragon Empires Gazetteer, Guide to the River Kingdoms, Heart of the Jungle, Inner Sea World Guide, Lords of Chaos - Book of the Damned, Volume 2, Pathfinder Campaign Setting: Distant Worlds, Princes of Darkness - Book of the Damned, Volume 1, Seekers of Secrets - A Guide to the Pathfinder Society, Technology Guide, Pathfinder Society Primer, Ultimate Campaign, Weapon Master's Handbook, Advanced Class Origins, Adventurer's Armory, Adventurer's Armory 2, Alchemy Manual, Andoran, Spirit of Liberty, Animal Archive, Armor Master's Handbook, Blood of Angels, Blood of Fiends, Blood of Shadows, Blood of the Beast, Blood of the Moon, Blood of the Elements, Blood of the Night, Champions of Balance, Champions of Corruption, Champions of Purity, Cheliax, Empire of Devils, Cities of Golarion, Critical Fumble Deck, Demon Hunter's Handbook, Dirty Tactics Toolbox, Divine Anthology, Dragon Empires Primer, Dragonslayer's Handbook, Dungeoneer's Handbook, Dwarves of Golarion, Elves of Golarion, Faction Guide, Faiths of Balance, Faiths of Corruption, Faiths of Purity, Familiar Folio, Gnomes of Golarion, Goblins of Golarion, Elemental Master's Handbook, Faiths & Philosophies, Halflings of Golarion, Heroes of the Streets, Heroes of the Wild, Humans of Golarion, Inner Sea Bestiary, Inner Sea Intrigue, Inner Sea Magic, Inner Sea Primer, Inner Sea Gods, Inner Sea Combat, Inner Sea Races, Andoran, Birthplace of Freedom, Artifacts and Legends, Bastards of Golarion, Beginner Box, Knights of the Inner Sea, Kobolds of Golarion, Legacy of Dragons, Magical Marketplace, Melee Tactics Toolbox, Monster Codex (Player Options Only), Monster Summoner's Handbook, Mythic Adventures, Orcs of Golarion, People of the North, People of the River, People of the Sands, People of the Stars, Pirates of the Inner Sea, Qadira, Gateway to the East, Quests & Campaigns, Ranged Tactics Toolbox, Sargava the Lost Colony, Spymaster's Handbook, Taldor, Echoes of Glory, Undead Slayer's Handbook, Varisia, Birthplace of Legends, Carrion Crown Player's Guide, Council of Thieves Player's Guide, Curse of the Crimson Throne Player's Guide (Conversion), Pathfinder RPG for Players, Jade Regent Player's Guide, Kingmaker Player's Guide, Legacy of Fire Player's Guide (Conversion), Mummys Mask Players Guide, Reign of Winter, Part 1: The Snows of Summer, Reign of Winter Player's Guide, Rise of the Runelords Adventure Path, Second Darkness Player's Guide (Conversion), Serpent's Skull Player's Guide, Shattered Star Player's Guide, Shattered Star, Part 1 - Shards of Sin, Skull and Shackles Player's Guide, City of Strangers, Inner Sea Faiths, Chronicle of the Righteous, Curse of the Crimson Throne, Chapter 1 - Edge of Anarchy (Conversion), Curse of the Crimson Throne, Chapter 2 - Seven Days to the Grave (Conversion), Curse of the Crimson Throne, Chapter 3 - Escape from Old Korvosa (Conversion), Curse of the Crimson Throne, Chapter 4 - A History of Ashes (Conversion), Curse of the Crimson Throne, Chapter 5 - Skeletons of Scarwall (Conversion), Curse of the Crimson Throne, Chapter 6 - Crown of Fangs (Conversion), Hell's Vengeance Player's Guide, Ironfang Invasion Player's Guide, Ironfang Invasion, Chapter 1 - Trail of the Hunted, Ironfang Invasion, Chapter 2 - Fangs of War, Ironfang Invasion, Chapter 3 - Assault on Longshadow, Ironfang Invasion, Chapter 4 - Siege of Stone, Iron Gods Player's Guide, Second Darkness, Chapter 1 - Shadow in the Sky (Conversion), Second Darkness, Chapter 2 - Children of the Void (Conversion), Second Darkness, Chapter 3 - The Armageddon Echo (Conversion), Second Darkness, Chapter 4 - Endless Night (Conversion), Second Darkness, Chapter 5 - A Memory of Darkness (Conversion), Second Darkness, Chapter 6 - Descent into Midnight (Conversion), Skull and Shackles, Chapter 1 - The Wormwood Mutiny]

**Comment by LegacyKing** [comment]
But no issue for the character sheet preview, but some interesting mismatches in the data:

20:34:57.661 SEVERE Thread-9 LstUtils:139 Invalid Token - does not contain a colon: 'TYPE.AttackOption' in Ability Piranha Strike of Campaign: Sargava the Lost Colony; SourceFile: file:/C:/Projects/pcgen/pcgen/data/pathfinder/paizo/player_companion/sargava_the_lost_colony/stlc_feats.lst
20:35:17.180 SEVERE Thread-9 LstObjectFileLoader:570 PObject Mule not found; .COPY skipped.
20:35:17.184 SEVERE Thread-9 LstObjectFileLoader:570 PObject Scale Mail Barding (Base) not found; .COPY skipped.
20:35:17.867 LSTERROR Thread-9 LstObjectFileLoader:626 file:/C:/Projects/pcgen/pcgen/data/pathfinder/paizo/player_companion/adventurers_armory/aa_equip.lst (236): PObject Pack Animal (Donkey/Mule) not found; .MOD skipped.
20:35:17.873 LSTERROR Thread-9 LstObjectFileLoader:626 file:/C:/Projects/pcgen/pcgen/data/pathfinder/paizo/player_companion/armor_masters_handbook/amh_equip_arms_armor.lst (28): PObject Trained Barding not found; .MOD skipped.
20:35:29.78 SEVERE Thread-9 AbilityCategory:697 Unconstructed Reference: Ability Category Special Ability Aasimar ~ Unnatural Aura
20:35:46.429 SEVERE Thread-9 AbilityCategory:697 Unconstructed Reference: Ability Category Android Race Trait Android ~ Constructed
20:35:46.429 SEVERE Thread-9 AbilityCategory:697 Unconstructed Reference: Ability Category Android Race Trait Android ~ Emotionless
20:35:46.431 SEVERE Thread-9 AbilityCategory:697 Unconstructed Reference: Ability Category Android Race Trait Android ~ Exceptional Senses
20:35:46.431 SEVERE Thread-9 AbilityCategory:697 Unconstructed Reference: Ability Category Android Race Trait Android ~ Languages
20:35:46.432 SEVERE Thread-9 AbilityCategory:697 Unconstructed Reference: Ability Category Android Race Trait Android ~ Nanite Surge
20:36:05.200 SEVERE Thread-9 ReferenceContextUtilities:62 Found Ability Category FEAT Piranha Strike  that had association: Off-Hand but was not an object with CHOOSE
20:36:30.264 WARNING AWT-EventQueue-0 CharacterManager:261 The following warnings were encountered while loading Rie.pcg
20:36:30.265 WARNING AWT-EventQueue-0 CharacterManager:272 * Unable to find follower at Kiyo.pcg

**Comment by LegacyKing** [comment]
Also the "30+ sources" is actually 142 by my count.

**Comment by demib84** [comment]
Must have been thinking of an earlier time. Though pathfinder has a crap ton of books.

**Comment by LegacyKing** [comment]
Bottom line - Problem was with EQMODS with the same name, and TYPE assignment but different KEYs. Should be addressed now.

**Comment by mjmeans** [comment]
If this was resolved in an OS fix, then I wont be able to test it until the next dev release or nightly build as I cannot build it myself. Is someone working on getting nightly build to work again?
