### ISSUE TITLE
Nightly autobuilds working?

### ISSUE THREAD

**Issue by mjmeans** [PCGen/pcgen#4146]
I tried to go to http://pcgen.org/download/ and click on the "Autobuilds – development" link and the "Download Autobuild" link and I'm seeing "Built at 2017-04-08 00:16, +1000 for PCGen Version 6.07.02-SNAPSHOT." So it appears that the autobuilds are broken. Maybe that section of the web page should be commented out until some time later when auto builds are working again since the 6.07.02-SNAPSHOT version seems to serve no useful purpose any more.

Perhaps the GitHub "releases" feature could be used for autobuilds instead.

**Comment by LegacyKing** [comment]
@thpr when Jenkings is back up on the new server - please close this.

Thanks,

**Comment by LegacyKing** [comment]
Project pretty much archived. Cleaning up last minute bugs and prepping for the final releases. Closing this.
