### ISSUE TITLE
Mithral shirt ACP & MDB are wrong

### ISSUE THREAD

**Issue by ghorbey** [PCGen/pcgen#4154]
Hi,

Mithral shirt has an Armor Check Penalty of -3 and a Max Dex Bonus of +3, which is wrong. (It should be 0 and +6)

Same if you equip a Burglar's buckler, or an outfit, which shouldn't modify ACP & MDB but these items set them at -3/+3.

Ghorbey

**Comment by djlimmer** [comment]
Check to see if your character is carrying a medium load; that is
another way a character can have an ACP of -3 and a Max Dex bonus of +3.
DS/DL

**Comment by ghorbey** [comment]
Hi,

You're right. Is there any way to know from where each bonus/malus/modifier came from?

Sorry for the false alert.

Ghorbey
