### ISSUE TITLE
Starfinder Issues when printing sheet

### ISSUE THREAD

**Issue by msbranin** [PCGen/pcgen#4156]
When you look at a weapon on the char sheet tab it shows criticals like Burn 1d4 But .. When you print the character sheet the criticals are all missing instead they all say
none X0

**Comment by LegacyKing** [comment]
Can you email a character pcg file to help reproduce this, also, what csheet are you using?

**Comment by LegacyKing** [comment]
So you want this instead?
[Kimmie.pdf](https://github.com/PCGen/pcgen/files/2281754/Kimmie.pdf)

**Comment by LegacyKing** [comment]
Here is the PR -- https://github.com/PCGen/pcgen/pull/4166
