### ISSUE TITLE
[Starfinder] Solarian weapon not working with weapon focus

### ISSUE THREAD

**Issue by TheReadError** [PCGen/pcgen#4161]
A solarian weapon is an advanced melee weapon. When I choose weapon focus advanced melee weapon, it doesn't affect my solarian weapon. 

Version 6.07.08

**Comment by LegacyKing** [comment]
Can you give me the page that states that? I can fix easily, just need to verify.

**Comment by TheReadError** [comment]
page 102 top left

"Your solar weapon functions as a one-handed kinetic
advanced melee weapon, and you’re automatically proficient
with it."

**Comment by LegacyKing** [comment]
https://github.com/PCGen/pcgen/pull/4163

**Comment by LegacyKing** [comment]
https://pcgenorg.atlassian.net/projects/DATA/issues/DATA-3706?filter=addedrecently&orderby=priority%20DESC
