### ISSUE TITLE
homepage links to bug reports are wrong

### ISSUE THREAD

**Issue by cnschu** [PCGen/pcgen#4268]
on the homepage at http://pcgen.org/contribute/ there are two links who claim to link to an description how to report bugs.

Both links don't link to any bug report functionality.

Both links should be corrected, to point to https://github.com/PCGen/pcgen/issues/

**Comment by LegacyKing** [comment]
Hi, we don't use Github to report issues, we use Jira. The link on that page correctly points to either the documentation home page, not sure why, but the bug report correctly points to --> pcgenorg.atlassian.net
