### ISSUE TITLE
menu option Help / Help open internet explorer and not the default browser (6.07.08)

### ISSUE THREAD

**Issue by cnschu** [PCGen/pcgen#4270]
Version: 6.07.08 (Windows)

actual behavior:
- select menu "Help"
- select menu item "Help"
- internet explorer opens with documentation URL

expected behavior:
- select menu "Help"
- select menu item "Help"
- default brower opens with documentation URL

**Comment by LegacyKing** [comment]
Can anyone take a look at the code to use the system default browser?

**Comment by grimreaper** [comment]
I have an idea, but no way to test it.  Wil give you a patch to try in a bit.

**Comment by grimreaper** [comment]
hrm, I was mis-remembering the code and it looks correct by inspection. Can you please try grimreaper:eax/fixwindowsbrowser/maybe and paste the logging output. This should help figure out where it might be going wrong.

**Comment by cnschu** [comment]
@grimreaper:
who do you talking to?

**Comment by grimreaper** [comment]
@cnschu sorry for missing your comment. I was hoping you could run pcgen with the branch I mentioned. It has some logging around what might be the cause of what you're seeing.

**Comment by grimreaper** [comment]
Closing for now as others don't have the same issue and I can't fix the issue without being able to replicate. Let me know if you can't apply my branch or if I need to recreate for some reason.

Do other Java applications work for you?
