### ISSUE TITLE
Pathfinder Magus Deep Marshal Armor Prof not applied

### ISSUE THREAD

**Issue by KuangEleven** [PCGen/pcgen#4271]
According to sources, the Deep Marshal archetype of the Pathfinder Magus should have Medium Armor Proficiency at first level. The sources *seem* to back this up, although it is not being applied properly when used in an actual character. Character file attached.

[Hudgrim Goldspotter.zip](https://github.com/PCGen/pcgen/files/2416335/Hudgrim.Goldspotter.zip)

Source snippet:

Deep Marshal			KEY:Magus Archetype ~ Deep Marshal									CATEGORY:Archetype		TYPE:Archetype.MagusArchetype		DESCISPI:YES	DESC:According to dwarven legend, the first deep marshals were handpicked by King Taargick himself to create massive tunnels to aid in the dwarven exodus to Golarion's surface during the Quest for Sky. Largely unseen by visitors, the deep marshals have survived into the modern era as keepers, protectors, and repairers of the myriad of stony passages that travel around, through, and under the Five Kings Mountains. Although the vast majority of deep marshals are dwarves, a few non-dwarves have earned enough trust to be trained as deep marshals, or have learned the same techniques from studying old dwarven spellbooks.		PRECLASS:1,Magus=1		PREMULT:1,[PREABILITY:1,CATEGORY=Archetype,Magus Archetype ~ Deep Marshal],[!PREFACT:1,ABILITIES,Magus_Archetype_Proficiencies=True,Magus_Archetype_Spells=True,Magus_Archetype_ArcanePool=True,Magus_Archetype_SpellCombat=True,Magus_Archetype_Spellstrike=True,Magus_Archetype_Arcana3=True]																																									ABILITY:Magus Class Feature|AUTOMATIC|Deep Marshal ~ Weapon and Armor Proficiency|PRECLASS:1,Magus=1	ABILITY:Magus Class Feature|AUTOMATIC|Deep Marshal ~ Deep Spellcasting|PRECLASS:1,Magus=1	ABILITY:Magus Class Feature|AUTOMATIC|Deep Marshal ~ Bound by Tradition|PRECLASS:1,Magus=1	ABILITY:Magus Class Feature|AUTOMATIC|Deep Marshal ~ Miner's Focus|PRECLASS:1,Magus=3																																		FACT:Magus_Archetype_Proficiencies|true	FACT:Magus_Archetype_Spells|true	FACT:Magus_Archetype_ArcanePool|true	FACT:Magus_Archetype_SpellCombat|true	FACT:Magus_Archetype_Spellstrike|true	FACT:Magus_Archetype_Arcana3|true	FACT:Magus_CF_ArmorProficiency|true	FACT:Magus_CF_Arcana3|true																																																																																																				COST:0	SOURCEPAGE:p.28	ASPECT:Archetype Base Class|Magus

**Comment by KuangEleven** [comment]
Looking a little more into it, it looks like it is applying reduced spell failure while wearing medium armor, but not the standard armor prof bonus

**Comment by KuangEleven** [comment]
If I level the Deep Marshal to 7, where the base Magus would get Medium prof, he does receive it

**Comment by LegacyKing** [comment]
Okay, Proficiencies added.  Fix bug: DATA-3731 #4280
