### ISSUE TITLE
ysoki size issue

### ISSUE THREAD

**Issue by ysoki** [PCGen/pcgen#4286]
Although in the race tab, Ysoki are definitely classed as small, on the summary tab, the character is classed as medium.  This is also true when using the auto-resize function for equipment.  All armors and weapons resize to medium automatically.  It's not a major issue, but a little annoying when you don't realise at first that the auto-resize didn't resize your equipment until after you input it all!  Thought I could save some others that issue.

**Comment by LegacyKing** [comment]
![image](https://user-images.githubusercontent.com/2759875/46331805-66986b80-c5ce-11e8-94be-9e0db031aafb.png)

I believe the issue is fixed, and will be available in he 6.07.09 release.

**Comment by LegacyKing** [comment]
Though, the Small is Medium and Medium is Small issue does persist.
