### ISSUE TITLE
[Starfinder] 3rd level weapon specialisation damage bonus added twice

### ISSUE THREAD

**Issue by TheReadError** [PCGen/pcgen#4294]
2 months ago, I opened a ticket (#4161 ) to correct the type of the solarian weapon.

Since then, the weapon specialisation damage bonus seems to be added twice.

example : my character was level 5 with 18 str  and the damage was 1d6+9 (+4 str + lvl 5) before the modification.
it became 1d6+14 (+4str +  2xlvl5 ?) after the modification.

after I became lvl 6, the damage became 2d6 + 16 ( +4 str + 2xlvl6 ?).  (2d6 is normal at lvl 6 for the solarian weapon)

Also, in the skills tab, if I select All skills in the dropdown on the right, it displays the same thing as All usable skills. I don't see all skills.

**Comment by LegacyKing** [comment]
Fixed the issue.

**Comment by LegacyKing** [comment]
FYI - skills tab won't fully function due to how I had to set up skills.
