### ISSUE TITLE
Occultist Mental Focus calculates wrong.

### ISSUE THREAD

**Issue by DarkDeed** [PCGen/pcgen#4346]
Occultist mental focus should be Occultist level+ his intelligence mod. Instead it shows weird numbers. On my lvl 11 occultist with 16 intelligence it shows 7 mental focus points for some reason.

**Comment by LegacyKing** [comment]
[oa_abilities_class.zip](https://github.com/PCGen/pcgen/files/2546411/oa_abilities_class.zip)

Try this patch.

**Comment by LegacyKing** [comment]
I cleaned up the formula that calculates the points to exclude the Favored Class bonus. The only other thing that would impact the end value is Archetypes.
