### ISSUE TITLE
Pathfinder: Sylph's Rogue Skill Bonuses

### ISSUE THREAD

**Issue by AsterITA** [PCGen/pcgen#4363]
It seems that sylph's favored class bonus for rogue doesn't work well, if i select it twice it should give 1 point in both skills instead it gives 4 points in each one.
Can you guys check it out? I found the line in which the bonus is described:
https://github.com/PCGen/pcgen/blob/1dfd8b9f7fa2cbc72703f08b94a61c213d5d1d0f/data/pathfinder/paizo/roleplaying_game/advanced_race_guide/arg_abilities_race.lst#L1184

You can reproduce it with the following character: [Eydan.zip](https://github.com/PCGen/pcgen/files/2563043/Eydan.zip)

**Comment by LegacyKing** [comment]
Fix bug: DATA-3762 - [ARG] Sylph Rogue Favored Bonus values incorrect #4379

**Comment by AsterITA** [comment]
> 
> 
> [advanced_race_guide.zip](https://github.com/PCGen/pcgen/files/2583646/advanced_race_guide.zip)
> 
> Just in case you wanted to test this.

I can confirm the bonus working! Thanks!
