### ISSUE TITLE
Feats do not have correct requirements

### ISSUE THREAD

**Issue by Krulvis** [PCGen/pcgen#4385]
Feats from the Inner Sea Gods do not have the correct requirements. If you make a Life mysteries Oracle with channel energy (cure) it cannot take the feats that require xd6's of channel because they are checked using a cleric specific channel variable: '_ClericChannelPositiveEnergyDice at least 3, var: ClericChannelNegativeEnergyDice at least 3_'.

**Comment by LegacyKing** [comment]
Fix in place, but need to clean the entire file.

**Comment by LegacyKing** [comment]
https://github.com/PCGen/pcgen/pull/4454
