### ISSUE TITLE
possible alch bug  but not sure.

### ISSUE THREAD

**Issue by tmb01** [PCGen/pcgen#4679]
Hi, 
I build out an alch/monk but when I create him I can never see any formulas on the spell page. Is this on me being blind or is this a bug? I attached the character for reference.
[Tim Pines.zip](https://github.com/PCGen/pcgen/files/2665081/Tim.Pines.zip)

**Comment by evilpixie87** [comment]
Alchemists must add any spells they have in their formula book, much like a wizard must add them to his spellbook. You have no spells in your book, so there are none to display!
