### ISSUE TITLE
Program hang when switching from Special Mount sheet to PC sheet

### ISSUE THREAD

**Issue by jjhritz** [PCGen/pcgen#4846]
6.08.00 RC3 hangs when I try to change from one character tab to another while I have the Character Sheet open.  In my particular case, it's been happening as I try to fill out my Paladin and his Roc Special Mount; switching from one tab to the other while a Character Sheet is open causes the cursor to change to the "loading" symbol (blue circle on my Win10), where it remains indefinitely.  

Notably, the menu bar at the top of the PCGen window _can_ be interacted with; clicking the "close window" button will cause PCGen to display a dialogue asking "Would you like to save your unsaved changes?"  However, clicking any of the buttons in the dialogue causes the dialogue to disappear and no further dialogues to appear, even if the ordinarily would.  The characters are also not saved and the PCGen window does not close.  The only way to close the program is to end the process from Task Manager.

I've sent the affected character sheets (which use some homebrew content that is also included) to HELP@pcgen.org.

**Comment by LegacyKing** [comment]
The Help email address no longer functions. Jump on Discord to submit any file or the JIRA is the best bet for actual bugs.

**Comment by LegacyKing** [comment]
@evilpixie87 or @Llisandur can you follow up on this issue?  Thanks

**Comment by jjhritz** [comment]
Ah, was wondering why it bounced.  Will do.
