### ISSUE TITLE
(Pathfinder)Rapid Reload shows nothing to select

### ISSUE THREAD

**Issue by megatog615** [PCGen/pcgen#5086]
Using 6.09.00(latest git as of today).

After taking the Rapid Reload feat, Rapid Reload Selection shows no options in the selection box.

**Comment by LegacyKing** [comment]
Just an FYI - The data monkeys don't monitor the issues tab over here often. It's best to use the tracking system https://pcgenorg.atlassian.net/ 

I'll see what I broke though.

**Comment by LegacyKing** [comment]
https://github.com/PCGen/pcgen/pull/5160

**Comment by megatog615** [comment]
Seems to work now, it is just lacking firearms(only shows crossbows), in my quick test.

**Comment by LegacyKing** [comment]
Uh, isn't that what the feat from Core Rules is supposed to show?
