### ISSUE TITLE
Bloodline keys for draconic aren't the same as Dragon Disciple

### ISSUE THREAD

**Issue by woofdunlap** [PCGen/pcgen#5143]
When adding a level of Dragon Disciple to a sorcerer with draconic bloodline.  I have to remove the draconic blood line and then add it back in as a Dragon Disciple.

![bloodline 1](https://user-images.githubusercontent.com/14932423/51763567-c340fa00-2087-11e9-99bc-cc26fa58f999.png)
![bloodline 2](https://user-images.githubusercontent.com/14932423/51763590-c936db00-2087-11e9-954c-cbb315147d55.png)
![bloodline 3](https://user-images.githubusercontent.com/14932423/51763605-cf2cbc00-2087-11e9-89c2-42953ab30c4b.png)
![bloodline 4](https://user-images.githubusercontent.com/14932423/51763614-d3f17000-2087-11e9-9926-abfe408fe0e8.png)
![bloodline 5](https://user-images.githubusercontent.com/14932423/51763617-d784f700-2087-11e9-9cff-826cb732c5a9.png)
![bloodline 6](https://user-images.githubusercontent.com/14932423/51763621-db187e00-2087-11e9-9e4e-ff74e696e4e2.png)
![bloodline 7](https://user-images.githubusercontent.com/14932423/51763648-de136e80-2087-11e9-9704-51223b0a06e1.png)

**Comment by Llisandur** [comment]
This was a design decision when reworking the bloodlines to the current design. Dragon Disciple does not require being a sorcerer to take, but it does require sorcerers that are also dragon disciples must have the draconic bloodline. This was the easiest way to force users to use the draconic bloodline--both abilities grant the same bloodline ability, but they set up some variables slightly different.
