### ISSUE TITLE
Issues with pcgen.org web site and help@pcgen.org email address...

### ISSUE THREAD

**Issue by perlygatekeeper** [PCGen/pcgen#5298]
Who maintains the website at pcgen.org.  Many links (including FAQ/Documentation) lead to 404 errors.

I tried to offer help following the "Volunteer!" link on pcgen.org:

_If you feel you can contribute, email help@pcgen.org with the subject line “I want to help!”. Tell us if there are any areas you are especially keen to work on, and mention any skills or experience that might be relevant._

To which I finally got the response:

**Delivery Status Notification (Failure)
Mail Delivery Subsystem <mailer-daemon@googlemail.com>

Message not delivered
--
There was a problem delivering your message to help@pcgen.org. See the technical details below.

The response was:
The recipient server did not accept our requests to connect. Learn more at https://support.google.com/mail/answer/7720 [pcgen.org 159.203.101.162: timed out]**

**Comment by LegacyKing** [comment]
@Nylanfs I thought we scrubbed all references to the @pcgen email addresses?

**Comment by perlygatekeeper** [comment]
Is there a different email address, I still want to volunteer.

**Comment by LegacyKing** [comment]
Join our Discord and we can talk --> https://discord.gg/A6hWjzw

**Comment by perlygatekeeper** [comment]
sorry, too late now.  Tomorrow?

**Comment by LegacyKing** [comment]
Did you ever jump on and chat with a volunteer?

**Comment by LegacyKing** [comment]
Closing this out.
