### ISSUE TITLE
Cardinal Archetype modified skill points not being applied at lvl 1

### ISSUE THREAD

**Issue by Muzouka** [PCGen/pcgen#5321]
Skill points for a level 1 Cleric with the Cardinal archetype is not reflecting modified values. It is still showing base skill point of 2 instead of 6.

**Comment by LegacyKing** [comment]
@grimreaper this is more code than Data. Skill pools are not adjustable easily after a class level is assigned. Stefan managed to have altered Intelligent scores retroactively adjust the pools, can you see if this would be feasible to implement for classes where we need to alter? JEP would be BONUS tag. @thpr has not implemented Skill Pools for the Formula System yet.

**Comment by LegacyKing** [comment]
This has a JIRA ticket assigned - https://pcgenorg.atlassian.net/browse/CODE-3484

Closing this issue for the time being. Java Code support will be required.
