### ISSUE TITLE
Line ending issue in shell script

### ISSUE THREAD

**Issue by moorepants** [PCGen/pcgen#5333]
On Ubuntu 18.10 I'm getting an error that seems to do with Mac line endings in the startup shell script.

```
wget https://github.com/PCGen/pcgen/releases/download/6.06.01/pcgen-6.06.01-full.zip
unzip pcgen-6.06.01-full.zip
cd pcgen
./pcgen.sh
```

error is

```
bash: ./pcgen.sh: /bin/sh^M: bad interpreter: No such file or directory
```

**Comment by moorepants** [comment]
Also:

```
$ /bin/sh pcgen.sh 
pcgen.sh: 2: cd: can't cd to .
: not found: pcgen.sh: 
pcgen.sh: 7: pcgen.sh: Syntax error: word unexpected (expecting "in")
```

**Comment by LegacyKing** [comment]
Hi, that's the 2+ year old release. Please give 6.08.00 RC4 a try. Thanks!

**Comment by moorepants** [comment]
When I go to the website here: http://pcgen.org/download/ It says that 6.06.01 is the current stable release and that is what the giant download buttons point to.
