### ISSUE TITLE
Issue with Ranger SAB~Wild Empathy 

### ISSUE THREAD

**Issue by floridaairpirate** [PCGen/pcgen#5422]
I believe there is an issue with the Ranger Special Ability ~ Wild Empathy.  It shows up under the class feat tab, but not on the standard tab.  I noticed it while trying to apply the Skilled Trainer feat from Quent. Ranger II source.  I looked thru the rsrd_abilities_class.lst data file from data/35e/wizard_of_the_west_coast/rsrd/basics directory... noticed the entry for Ranger Wild Empathy was missing "ABILITY:Special Ability|AUTOMATIC|Wild Empathy", that is listed under the Druid (which works).  Tired to correct it on my side, but unsuccessful.  I am noob.  Still learning how the coding works, so i apologize.  If you offer suggestion on correction, I'll be happy to give it a shot.  Also, would love suggestion on what software to use... notepad works, but takes a while to count tab spaces.  Thanks, Bill

**Comment by LegacyKing** [comment]
Wow, SAB... Geez, that's ancient usage. Should be fairly easy to fix in theory.

**Comment by LegacyKing** [comment]
https://github.com/PCGen/pcgen/pull/5423
