### ISSUE TITLE
Handaxe not working properly on a Monk D&D 5e

### ISSUE THREAD

**Issue by BarbaAlGhul** [PCGen/pcgen#5551]
So, I created from scratch a Human Monk and I chose the Handaxe to be my weapon, but it's giving me high numbers of bonuses and I couldn't figure out why.

Here is the character:

[Test Monk.zip](https://github.com/PCGen/pcgen/files/3170173/Test.Monk.zip)

The bonus for the dart weapon looks fine.

**Comment by LegacyKing** [comment]
https://pcgenorg.atlassian.net/browse/DATA-3932

**Comment by LegacyKing** [comment]
https://github.com/PCGen/pcgen/pull/5562
