### ISSUE TITLE
Extra feat when Disenchanter Archetype is chosen for Warpriest 

### ISSUE THREAD

**Issue by Muzouka** [PCGen/pcgen#5762]
When the Disenchanter Archetype is chosen for the Warpriest a Disenchanter Bonus feat shows up in Feats & Abilities.
![image](https://user-images.githubusercontent.com/36632341/58377187-33677a00-7fad-11e9-91ce-84dfde024388.png)

**Comment by LegacyKing** [comment]
Fixed. Opening JIRA to track.
