### ISSUE TITLE
"Hunter's Surprise"  (Advanced Rogue Talent) mistakenly stored as regular Talent

### ISSUE THREAD

**Issue by AaronSofaer** [PCGen/pcgen#5770]
All of the sources I can find online (ex: https://www.d20pfsrd.com/classes/core-classes/rogue/rogue-talents/paizo-rogue-advanced-talents/hunter-s-surprise-ex ) have Hunter's Surprise as an Advanced Talent. PCGen has it as a regular talent.

Apologies if this is the wrong place to file this bug. Present in 6.08.00 RC6. Source is the Advanced Player's Guide.

**Comment by LegacyKing** [comment]
If you can post this on our actual bug tracker:  https://pcgenorg.atlassian.net

**Comment by LegacyKing** [comment]
This would be considered a DATA Bug

**Comment by LegacyKing** [comment]
I don't see this as an error. Advanced Rogue Talents are when you're level 10. Unless you want me to rewrite them all. Let's chat - https://discord.gg/ede6jH9 I'll be on for maybe another hour.

**Comment by AaronSofaer** [comment]
Discussed on Discord and filed a JIRA, https://pcgenorg.atlassian.net/browse/CODE-3424 (accidentally made it a CODE ticket and can't move it).
