### ISSUE TITLE
Can't load PCGen v6.09

### ISSUE THREAD

**Issue by TwistedFaith84** [PCGen/pcgen#5912]
I'm not sure why but I'm pretty sure it has something to do with my 10+ year old computer.... But I've tried numerous times to install v6.09 (downloading from official website each time) and it seems like it installs just fine but when I go to run it I get the message asking me where I want the settings file and when I choose and click ok it seems like it's starting to load up (in the list of processes on Task Manager) but after a few seconds it just disappears and doesn't load anything.

I do also have v6.08 and that works and loads just fine (with a few exceptions but thats cause I'm using BahamutsDragon's Data as well)

Anyways I'm running on

![sysinfo](https://user-images.githubusercontent.com/11351824/59610020-26d2cf00-90de-11e9-88f4-262c057294b9.jpg)

So not sure what it could be on my end but I'm sure it's on my end.

**Comment by LegacyKing** [comment]
6.09 is unstable, there is a fix, but I haven't been able to release it. For the time being please use 6.08.00 RC6
