### ISSUE TITLE
Only 1 HP gained at each level

### ISSUE THREAD

**Issue by nicorio** [PCGen/pcgen#5917]
Using PCGen 6.08.00 RC6 on Win10 and 6.07.06 on MacOS for building Starfinder characters, I only get 1 HP at each level instead of the number I'm supposed to gain with a selected class.
![levels](https://user-images.githubusercontent.com/469923/59883164-7c47fe00-93b4-11e9-8810-441789361bbe.png)
![Settings](https://user-images.githubusercontent.com/469923/59883165-7c47fe00-93b4-11e9-9fb3-a6d1acb191d2.png)

**Comment by LegacyKing** [comment]
Starfinder doesn't use HP rules. You get a set amount every level, with the only variables being your Constitution bonus and species.

**Comment by nicorio** [comment]
Indeed, it is a fix amount for each level, depending on the selected class, but it shouldn't be 1HP.
In the screenshot previously sent, I should have 6HP for Envoy, 6HP for Mechanic and 5HP for Technomancer, shouldn't I ?

**Comment by nicorio** [comment]
@LegacyKing : I don't know if you have been notified when my last message was published since this is a closed issue. What do you think of it?

**Comment by LegacyKing** [comment]
@nicorio I set the HP to 1 for expediency. It's a meaningless value. What is the end result on the character sheet? If that is wrong, then I'll act, but the dice roller for a non-existent dice that doesn't impact the end result is not something I want to refactor to make it show 0.

**Comment by nicorio** [comment]
The end result on the character sheet is good.
Thanks for the information.
