### ISSUE TITLE
PC-Gen LST Data Portability.

### ISSUE THREAD

**Issue by grabear** [PCGen/pcgen#5926]
Can .LST files be converted to other formats?  Is there an existing way for me to parse this data in another language such as python?

**Comment by LegacyKing** [comment]
Yes. The files are tab delimited text files. Any language should be able to parse the data in theory.

**Comment by grabear** [comment]
Hi @LegacyKing 

So (assuming there isn't a .LST parser out there already) I've begun working on my own via Python.

The data I'm using to experiment with is in the [cr_equip_general.lst](https://github.com/PCGen/pcgen/blob/master/data/pathfinder/paizo/roleplaying_game/core_rulebook/cr_equip_general.lst) file.

This seemed like an easy place to start, because of the way each block is formatted (granted I haven't really explored the other LST files yet).  I'm essentially able to produce 1 csv file per block.  So the `Adventuring Gear` block looks like this:

[.LST equipment parser gist](https://gist.github.com/grabear/c14a29d0d6b107221ce658987b91eb2e)

### Potential Issues
Some of the columns like the **QUALITY** column have "multiple values" so they have been grouped as a list.

### Question
* Would this be useful to the PCGen community?
* Do you have any tips for me proceeding?
* Are there any `Licensing` issues with this data?

**Comment by LegacyKing** [comment]
Sorry, sure share if you like. I'm sure someone would like it.
I don't have any advice. Good luck!
Just follow the licenses that are put into place.
