### ISSUE TITLE
Rondelero Duelist not available even when Taldor is selected for Region

### ISSUE THREAD

**Issue by Muzouka** [PCGen/pcgen#5985]
In PFS Organized Play Mode I cannot select the Rondelero Duelist Archetype even when I select  Taldor as my Region
![Region-Taldor](https://user-images.githubusercontent.com/36632341/63140293-0ce93600-c014-11e9-9d2e-ae6b5779e7cd.PNG)
![Rondelero Duelist not available](https://user-images.githubusercontent.com/36632341/63140296-0fe42680-c014-11e9-83cc-c26eabea1588.PNG)

**Comment by LegacyKing** [comment]
Everything appears correct in 6.09.01. Retry with that and if it doesn't work, please supply the character file (*.pcg)
