### ISSUE TITLE
Loading Source from Existing Character

### ISSUE THREAD

**Issue by daimeng** [PCGen/pcgen#5990]
Not sure if this is a bug, I'm on v6.08.00 RC7.
I can load character files, and the sources load with them, but they don't show up in the `Sources > Select Sources` Menu.
Basically, I want to add a new source that I missed.
Is this possible without repeating every one previously chosen manually?

**Comment by starcraftman** [comment]
Yeah, I can see this being annoying. If you forgot what you selected you can see it in the CAMPAIGN line of your character pcg file near the top. Just open it up with a text editor like notepad. At the moment, only option is to select them all again.

I'm making a patch to populate the advanced pane with the characters source selections so in future this case will be easy. I can't promise delivery in 6.08, depends on what gets backported.

**Comment by starcraftman** [comment]
Hmmm github didn't pickup the second PR. The merged fix landed in master with #6016 for posterity. Will be fixed at some point in future, though maybe not with 6.08.x .

**Comment by LegacyKing** [comment]
Backported
