### ISSUE TITLE
d20 Modern statblock1.htm Template does not display skills

### ISSUE THREAD

**Issue by pkovac** [PCGen/pcgen#6006]
## Step to reproduce:

Version: Both 6.08.00RC4 and 6.08.00RC7

1. Load PCG file contained in: [Eric Mckinney.zip](https://github.com/PCGen/pcgen/files/3585853/Eric.Mckinney.zip)
2. Switch to Character Sheet tab and select `statblock1.htm` as the template

## Actual behavior:

In the template preview, the "Skill:" section is blank.

[2019-09-06 18_09_21-Eric Mckinney pcg - MSRD Modern Mode - PCGen v6 08 00 RC7](https://user-images.githubusercontent.com/425845/64463300-833bfe00-d0d1-11e9-8332-5878dec5da9a.png)

## Expected Behavior:

The template preview displays a summary of total skill modifiers like one might expect in an NPC statblock.

**Comment by starcraftman** [comment]
I can confirm this bug on 6.08 branch, had to go down the rabbit hole of the template for this bug. A fix will be coming on a PR shortly. There was a strange disconnect between the behaviour when exporting with that template and the live preview tab.

**Comment by pkovac** [comment]
Thanks for the quick response and fix!
