### ISSUE TITLE
Ratfolk Alchemist favored class bonus issue

### ISSUE THREAD

**Issue by jlamberj** [PCGen/pcgen#6023]
When taking the bonus alchemist new discovery(+1/6) favored class bonus for ratfolk, no new bonus discoveries are granted until after the 6th instance of taking the favored class bonus. At this point the total discoveries available goes up by 6 instead of 1. On 6.08.00 RC7

**Comment by LegacyKing** [comment]
Character file? pcg please.

**Comment by howarjames** [comment]
I also had this issue with both 6.08.00 RC10 and 6.09.07. Here is the pcg as a txt file, I couldn't upload the pcg file to github without changing the file extension.
[Bivven.txt](https://github.com/PCGen/pcgen/files/12045941/Bivven.txt)
