### ISSUE TITLE
Is it ok to freely add armor upgrades on android upgrade slot ?

### ISSUE THREAD

**Issue by nicorio** [PCGen/pcgen#6037]
I have built a lvl 1 Android character, and am willing to add an upgrade into his upgrade slot.
Unless I missed it, it is not specified in the books that these upgrades are free, but rather that I can benefit from an upgrade slot even if I have no armor or if I wear an armor with no upgrade slots.
Still, in PC Gen, I can add any upgrade on this slot without spending any credit.
Did I miss the part where it says that Androids get a free armor upgrade or should I spend credit manually in the inventory?

**Comment by LegacyKing** [comment]
I'd have to read the rules, but I think the answer is no. However, we're in a transition state waiting for the program to handle the more complex interactions of the rules. PCGen is not infallible. It aids you get a proper character but I cannot make it 100%.

**Comment by LegacyKing** [comment]
Due to no code support, I rather doubt this will be addressed. I hope you found the official answer from Paizo though. Closing this out.

**Comment by nicorio** [comment]
I missed your previous message. Thank you very much for PCGen. It is indeed a great help for our group. I understand very well that it cannot be 100% compliant with all the rules.
