### ISSUE TITLE
Pathfinder: Point Blank Master missing Ranger "special" requirement

### ISSUE THREAD

**Issue by lathspell** [PCGen/pcgen#6039]
The Pathfinder Feat "Point Blank Master" is listed with the requirements: 

> "all of ( at least 1 Weapon Specialization ( TYPE=Ranged) FEAT) and at least Weapon Specialization with selected weapon" with source Paizo - Advanced Player's Guide p.167.

The following site though has an additional sentence:
* https://www.d20pfsrd.com/feats/combat-feats/point-blank-master-combat/
* https://paizo.com/threads/rzs2l394?New-Feat-Point-Blank-Master-Advanced-Players

> "Special: Starting at 6th level, a ranger with the archery combat style may select Point Blank Master as a combat style feat, but he must have Weapon Focus instead of Weapon Specialization in the selected weapon."

Therefore a pure ranger, can take "Point Blank Master", too, even if he cannot gain "Weapon Specialization" due to the lack of its "fighter lvl. 4" requirement.

**Comment by LegacyKing** [comment]
Uh, so not seeing any issue here. Ranger Style feat version of Point Blank Master has no Weapon Specialization requirement.

**Comment by lathspell** [comment]
Now I see what you mean, the same Feat is also in Feats -> Class Features -> Ranger Combat Style Feat but with different requirements. Confusing! :)
