### ISSUE TITLE
Esoteric Magus Unarmed Damage calculation incorrect

### ISSUE THREAD

**Issue by monyarm** [PCGen/pcgen#6097]
I just made a Magus 7/Monk 2 in pcgen, and he has the unarmed damage of a level 2

 monk, rather than a level 9 monk.

From d20pfsrd:
> Unarmed Strike: At 1st level, an esoteric gains Improved Unarmed Strike as a bonus feat. He also treats his magus levels as monk levels when determining the amount of damage he deals with his unarmed strikes.

Monastic Legacy has the same issue, with it i have the damage of a level 5 monk. It also has another issue, in that taking Ascetic Strike does not remove the Still Mind Requirement.

If i add Monk's robes on top of that, i have the unarmed damage of a level 8-11 monk. Rather than a level 17 monk (9 "monk" levels + 1/2 my levels in non-monk classes (7/2=3) + 5).

[Haruto Soma.pcg.txt](https://github.com/PCGen/pcgen/files/3877020/Haruto.Soma.pcg.txt)

**Comment by LegacyKing** [comment]
https://github.com/PCGen/pcgen/pull/6158
