### ISSUE TITLE
.pcg `Character Master/Follower` paths are hard coded

### ISSUE THREAD

**Issue by parkerault** [PCGen/pcgen#6118]
~I am trying to save a PC with an animal companion in a shared network folder. When I "save as" the PC into a file on the network folder, and save a copy of the animal companion in the same location, the path to the animal companion file is hard coded in the PC's file. When I attempt to open the PC on a second computer, it displays the error message "Unable to find follower at..." followed by the full path to the pcgen character directory on the first computer. Is it possible to save a copy of a character to another location with the animal companion included, or with the animal companion referenced as a relative path?~

Edit: Right after I posted this I was able to edit the character file and change the companion reference to a relative path (I figured it was an sqlite database or something so it didn't occur to me to try and open it in a text editor). This might be something to consider though; if a PC has a follower or animal companion, ask during the save process whether to include the companion's file as well.

**Comment by LegacyKing** [comment]
Each iteration we lose more companion functionalities. Used to be you could reload a missing companion, but that disappeared with 6.x series.

**Comment by LegacyKing** [comment]
@mertonmonk You want to take a look at this?

**Comment by LegacyKing** [comment]
Closing this out. Project is shutting down.
