### ISSUE TITLE
Pathfinder 1e Bard core rules

### ISSUE THREAD

**Issue by TomaszOcwieja** [PCGen/pcgen#6134]
if bard is low on charisma - the 5th 6th level spell slots are not available - tho should be https://www.d20pfsrd.com/classes/core-classes/bard/

**Comment by LegacyKing** [comment]
To learn or cast a spell, a bard must have a Charisma score equal to at least 10 + the spell level.  Does your Bard meet that requirement?

**Comment by TomaszOcwieja** [comment]
thats the problem - ive modified the bard - and it did not recalculate how much known spells should he have (bard had charisma of 15 - but then he had charisma of 16)
