### ISSUE TITLE
[BUG] Cannot Export character to Fantasy Grounds XML.

### ISSUE THREAD

**Issue by MTVExtreme** [PCGen/pcgen#6240]
On the latest release build v6.08.00 RC8, most times when I try to export a Pathfinder 1st ed character using the csheet_FantasyGrounds2_pc_PFc3.xml.ftl I receive an error. Porting these characters over to the newest experimental builds do not solve the problem.

Here is the current Sources used to create a lv 4 Samurai Kamie. The other character used a more expansive list.
![image](https://user-images.githubusercontent.com/5505510/79616950-507cce00-80d4-11ea-9bb4-2a7e7deb94e3.png)

Here is the log 
[Log.txt](https://github.com/PCGen/pcgen/files/4495410/Log.txt)

I am using Windows 10 Home v1909 OS Build 18363.720

Affected character files.

[characters.zip](https://github.com/PCGen/pcgen/files/4495449/characters.zip)

**Comment by LegacyKing** [comment]
Didn't like mythic...

**Comment by LegacyKing** [comment]
[csheet_FantasyGrounds2_pc_PFv3.xml.ftl.zip](https://github.com/PCGen/pcgen/files/4538685/csheet_FantasyGrounds2_pc_PFv3.xml.ftl.zip)

Give that version a test.

**Comment by MTVExtreme** [comment]
That didn't seem to work.

[log2.txt](https://github.com/PCGen/pcgen/files/4571070/log2.txt)

**Comment by Deepinthots** [comment]
I have an similar issue exporting to any format with the error being along the lines of an incorrect path. The source list is...extensive so maybe that is the issue
log of issue
[Log.txt](https://github.com/PCGen/pcgen/files/4737598/Log.txt)
character attempting to export
[Falad.zip](https://github.com/PCGen/pcgen/files/4737604/Falad.zip)

windows 10

**Comment by MTVExtreme** [comment]
Update on this, I believe it is something related to certain feats. Removing all the feats from some of these characters will fix this issue.

**Comment by LegacyKing** [comment]
That's not beneficial if you lose your feats though.

**Comment by LegacyKing** [comment]
The only error is it doesn't like the characters in the name `Baalgor "SNAKE EYES" Whitemane.TXT`

I can only guess the Quotes are the dislike there, which is odd.

**Comment by PokeyCA** [comment]
I found the errors in the export script.  There is no mythicFeat tag in PCGen, they are straight feats (at least for this output).  Here is the export file.
[csheet_FantasyGrounds2_pc_PFv3.xml.zip](https://github.com/PCGen/pcgen/files/5861783/csheet_FantasyGrounds2_pc_PFv3.xml.zip)

**Comment by williambbertram** [comment]
This happens every time I create a wizard, regardless of which feats I select. I have tried multiple Wizards, including absolute basic ones with no feats added.

I have created fighters, rogues, and clerics and the export works fine.

[pcgen.log](https://github.com/PCGen/pcgen/files/6777734/pcgen.log)

**Comment by PokeyCA** [comment]
> 
> 
> This happens every time I create a wizard, regardless of which feats I select. I have tried multiple Wizards, including absolute basic ones with no feats added. Something as simple as File / New Character, add one wizard level.
> 
> I have created fighters, rogues, and clerics and the export works fine.
> 
> I really like this export, because it creates actual Fantasy Grounds equipment items. If the character has a "Long Sword," the correct item in Fantasy Grounds is imported. The 3.5 export will create an item called "Long Sword," but it's just a new blank item in Fantasy Grounds. FG can't use it for calculating bonuses, etc. Unfortunately I can't export anything with a Wizard level currently.
> 
> [pcgen.log](https://github.com/PCGen/pcgen/files/6777734/pcgen.log)

Did you use the above export template, or the one that comes with PCGen (which has a known error)?

**Comment by williambbertram** [comment]
Oh, I'm sorry Pokey. I didn't realize that zip file was a corrected version. I thought you were providing more information about the bug. I'll give it a try. Thank you!

**Comment by MTVExtreme** [comment]
I did not realize this thread was still open my apologies. The file that PokeyCA added seemed to have resolved the issue that was occurring I will now close out this issue. Thanks for all the support!
