### ISSUE TITLE
[BUG] String opening quote missing in arg_abilities_builder.lst

### ISSUE THREAD

**Issue by NFodrea** [PCGen/pcgen#6259]
**Describe the bug**
I'm at work or I would just pull this down and fix it. In `arg_abilities_builder.lst` on line 272 there is what I assume to be a closing `"`. This either needs removed or an opening `"` to start the string is needed. Currently its reading the remaining 400 lines as part of the open string. 

**Screenshots**
![image](https://user-images.githubusercontent.com/19756516/81607506-cbb76400-93a2-11ea-8e3a-99130ca3b90f.png)

**Comment by LegacyKing** [comment]
Editors are like that. Luckily, lst doesn't see quotes as strings. But simple typo fix.

**Comment by LegacyKing** [comment]
Fixed.
