### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by matheustsa** [PCGen/pcgen#6348]
**Describe the bug**
When selecting "Dwarf" as your race, and choosing the racial subtype as "Elder Dwarf", you have the option to choose between two specific abilities of that subtype, "Magic Resistant" and "Stubborn". However, even if one of them is selected, the selection count available does not decrease. It still prevents you from selecting the two skills together, but does not decrease the available value. Which generates a "Tip" about it on the Summary screen.

**To Reproduce**
1. New character
2. Select Race: Dwarf
3. Go to "Feats & Abilities" tab
4. Go to "Racial Abilities" subtab
5. Click on "Dwarf Racial Subtype" in the box below
6. Select "Elder Dwarf" in the box above
7. Click on "Elder Dwarf Choice" in the box below
8. Select one of the abilities (Magic Resistant or Stubborn)
9. Check the counter below that didn't decrement
10. Go to "Sumary" tab, and check that the "things to be done" tip about "Elder dwarf choice remains to be selected" is there yet

**Expected behavior**
The "Elder Dwarf Choice" should decrement when abilities selected 

**Desktop (please complete the following information):**
 - OS: Windows 10 (last build)

**Character File**
[Unnamed 1.zip](https://github.com/PCGen/pcgen/files/5048947/Unnamed.1.zip)

**Comment by LegacyKing** [comment]
Have no issue with this: 
![image](https://user-images.githubusercontent.com/2759875/89753723-2dfd2f00-da8e-11ea-971f-7372af06248d.png)

**Comment by matheustsa** [comment]
It still happens to me...

![image](https://user-images.githubusercontent.com/28052029/90149597-0a223d80-dd5b-11ea-9dc0-babd4fbbcb12.png)

I don't know if this matters, but I'm using this pathfinder sources:

![image](https://user-images.githubusercontent.com/28052029/90149723-36d65500-dd5b-11ea-9576-4785b453febf.png)

**Comment by LegacyKing** [comment]
Okay. I tested against 6.09.05-dev.

**Comment by LegacyKing** [comment]
6.08.00 RC 8 was released around December 2019; the fix for this was uploaded March 2020. I've backported all the Patches for this year to date into 6.08, 6.08.00 RC 9 will have all those fixes.
