### ISSUE TITLE
[BUG] pcgen 6.09.05 - Starfinder problems

### ISSUE THREAD

**Issue by Tregis** [PCGen/pcgen#6410]
**Describe the bug**
Alien Archive 3 not showing up on load Sources

**Expected behavior**
Aliens Archive 3 should load

Fix:
In data\starfinder\paizo\master_loader.pcc  the following line needs to be adjusted:
PCC:@/starfinder/paizo/alien_archive_2/_starfinder_alien_archive_3.pcc
to
PCC:@/starfinder/paizo/alien_archive_3/_starfinder_alien_archive_3.pcc

**Comment by LegacyKing** [comment]
Added this to a PR.
