### ISSUE TITLE
wrong spell levels in player_companion/blood_of_fiends/bof_spells.lst

### ISSUE THREAD

**Issue by chopstyx** [PCGen/pcgen#6496]
The following spells in data/pathfinder/paizo/player_companion/blood_of_fiends/bof_spells.lst are listed as level 3 spells. They should be level 2. Could you change this, please?

- The Dance of Kindled Desires (Dance)
- They Rheumy Refrain (Sing)

Thanks.

**Comment by LegacyKing** [comment]
Missed this... https://pcgenorg.atlassian.net/ is the best place for bug reports. I'll try to hit this soon!

**Comment by LegacyKing** [comment]
Fixed.
