### ISSUE TITLE
[BUG] Muleback cords don't affect carrying capacity

### ISSUE THREAD

**Issue by snowe2010** [PCGen/pcgen#6562]
**Describe the bug**
Muleback cords should be equipable on the shoulders, but that doesn't seem to be an option, and when equipped in 'Carrying', it does not affect carrying capacity at all.

**Desktop (please complete the following information):**
 - OS: Windows 10

**Character File**

[Zook_Murnig.zip](https://github.com/PCGen/pcgen/files/7110417/Zook_Murnig.zip)

**Comment by LegacyKing** [comment]
You can only equip one Shoulders Slot item at a time. Remove your Cloak and you can wear it correctly.

**Comment by LegacyKing** [comment]
Verified when actually equipped the carry capacity does increase. Closing as a non-issue.
