### ISSUE TITLE
[BUG] Ability damage (Constitution) not applying

### ISSUE THREAD

**Issue by snowe2010** [PCGen/pcgen#6680]
**Describe the bug**
With my character, adding a temp bonus of Con Damage has no affect. The temporary score and temp modifier stay stuck at 14/+2, no matter how many times I remove it or add it. Also, adding it multiple times results in only a single Bonus on the right pane of the Temp Bonus screen, but multiple on the Character Sheet. Then you're unable to remove all the added bonuses until you close the sheet and reopen it. 

**To Reproduce**
1. Using the attached character. 
2. Add an `Ability Damaged (Constitution)` bonus of 2
3. Go to Character Sheet
4. Con isn't affected
5. Go add more ability damage
6. Now try to remove the damage from the right pane on `Temporary Bonus` 
7. Note there is no Con Damage on the right pane
8. go to character sheet
9. there is still con damage bonus applied 

**Expected behavior**
I expect con damage to apply
I expect to have multiple con damage modifiers on the right screen 
I expect to be able to remove one con damage and not the other

**Screenshots**
![image](https://user-images.githubusercontent.com/1534535/156899991-16740808-ec0a-4014-8ed6-88046cd18206.png)
![image](https://user-images.githubusercontent.com/1534535/156899996-49d4fa08-bd6c-475f-97c6-e33d9e80ef92.png)

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser: N/A
 - Version 6.09.05

**Character File**
Include a character *.pcg file that can be used to reproduce the issue.
[Zook_Murnig.zip](https://github.com/PCGen/pcgen/files/8191484/Zook_Murnig.zip)

**Additional context**
Seems like Temp Bonuses are very broken. This seems similar to the [other issue](https://github.com/PCGen/pcgen/issues/6556) I filed in regards to modifiers not adding correctly

**Comment by BlyatBeauty** [comment]
This has been an issue affecting my table for the last year or so. We've resorted to using Ability Drain in the program and writing down the actual condition elsewhere.

**Comment by LegacyKing** [comment]
Fixed
