### ISSUE TITLE
[BUG] 3.5 - Dragonfire Adept cannot take Ability Focus

### ISSUE THREAD

**Issue by Ed-Zero** [PCGen/pcgen#6689]
**Describe the bug**
3.5 - Dragonfire Adept cannot take Ability Focus, it says in the universal rules for the ability focus feat that it works for breath weapons, but you are unable to select it

**To Reproduce**
1. Open up a new character
2. make him a Dragonfire Adept
3. Try to select Ability Focus as your feat, it's red

**Expected behavior
[Dragonborn Adept.zip](https://github.com/PCGen/pcgen/files/8313208/Dragonborn.Adept.zip)
**
The expected behavior is to be able to select it, as the class gives you a breath weapon

**Screenshots**
![image](https://user-images.githubusercontent.com/36054876/159207318-0be0cde2-a295-4171-add6-8b13645b6bd1.png)

**Desktop (please complete the following information):**
 - OS: Win11
 - Browser: Firefox
 - Version: 98.0.1

**Character File**
[Dragonborn Adept.zip](https://github.com/PCGen/pcgen/files/8313210/Dragonborn.Adept.zip)

**Additional context**
If you could let me know what file to edit on my end to make this work before an update goes out, I would appreciate it for the sake of getting this quickly, as I need it on my character.

I also posted this issue on the Discord Support.

**Comment by LegacyKing** [comment]
Take a long break and see the issues piled up. This is not a supported class, it appears these books are homebrew. You'll need to fix the coding yourself, or ask whomever provided the data. 

Just to prove this, none of these books are found in the PCGen releases:
Faiths and Pantheons 
Drow of the Underdark 
Magic Item Compendium 
Complete Scoundrel 
Fiendish Codex II 
Cityscape (WotC) 
Complete Champion 
Complete Mage 
Complete Psionic 
Stormwrack 
Dragon Magic 
Tome of Battle: The Book of Nine Swords 
Player's Handbook II 
Tome of Magic 
Races of the Dragon 
Spell Compendium 
Champions of Valor 
Lords of Madness 
Magic of Incarnum 
Weapons of Legacy 
City of Splendors: Waterdeep 
Champions of Ruin 
3.5e ~ Heroes of Battle 
Races of Eberron 
Sandstorm 
Lost Empires of Faerun 
Complete Adventurer 
Races of Destiny 
Complete Arcane 
Draconomicon 
Libris Mortis 
Shining South 
Frostburn 
Monster Manual III 
Races of Stone 
Races of the Wild 
Complete Divine 
Expanded Psionics Handbook 
Player's Guide to Faerun 
Races of Faerun (35e) 
Unearthed Arcana (Complete) 
Complete Warrior 
Dungeon Master's Guide II 
Fiend Folio 
3.5e ~ Heroes of Horror 
Book of Exalted Deeds 
Miniatures Handbook 
Underdark 
Unapproachable East 
Arms and Equipment Guide 
Savage Species 
3.5e ~ Book of Vile Darkness 
Monster Manual II 
Epic Level Handbook 
Magic of Faerun 
Monster Compendium - Monsters of Faerun 
Fey Feature 
Spellbook Archive 
The Mind's Eye 
Dragons of Faerun - Web Enhancement - City of Wyrmshadows 
Dungeonscape 
Swiftblade 
Wizards of the Coast - Monster Manual 4 (35e) 
Dungeons & Dragons - Core Books
