### ISSUE TITLE
[BUG] Twinned Presence does not apply Intimidate trait bonus

### ISSUE THREAD

**Issue by joeykuhn** [PCGen/pcgen#6708]
**Describe the bug**
The Twinned Presence trait does not currently give the Intimidate skill a +1 trait bonus. 

**To Reproduce**
1. Have at least 1 level in Summoner
2. Have Ultimate Campaign loaded
3. Select Twinned Presence as a Trait
4. Look at character sheet and see that Intimidate bonus is not applied.

**Expected behavior**
Intimidate should get a +1 trait bonus from Twinned Presence, and it does not.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows x64
 - Version: 6.08.00

**Character File**
[Magnus Kinser.zip](https://github.com/PCGen/pcgen/files/8692505/Magnus.Kinser.zip)

**Additional context**
None

**Comment by joeykuhn** [comment]
I've never publicly contributed to an oss like this so I am not totally sure how to fix this officially, but all you have to do to fix this is go to ...\paizo\roleplaying_game\ultimate_campaign\uca_abilities_traits.lst and change line 159 to have "BONUS:SKILL|Intimidate|1|TYPE=Trait" instead of
"BONUS:SKILL|Intimidate|TYPE=Trait".

**Comment by LegacyKing** [comment]
Fixed
