### ISSUE TITLE
[BUG] Can no longer use "gradlew run" to start PCGen

### ISSUE THREAD

**Issue by megatog615** [PCGen/pcgen#6991]
**Describe the bug**
For years I have updated from git and used  "gradlew run" to start PCGen. Now, gradlew fails with an error:
`Error: --module-path requires module path specification`

Searching online for this problem has revealed a potential fix, removing `configuration = "compileOnly"` from build.gradle.

**To Reproduce**
1. cd to the git clone directory
2. run "gradlew run"
3. error should appear

**Expected behavior**
I expect the app to start but I understand if my preferred method of running PCGen isn't the intended method.

**Desktop (please complete the following information):**
 - OS: Debian 12/testing Linux AMD64

**Comment by karianna** [comment]
I've fixed this locally.

Remove the build.gradle block of code that says:

```
if (!System.getProperty('idea.active') && !(localOnly.toBoolean())) {
        configuration = "compileOnly"
}
```
