### ISSUE TITLE
How do I add a class archetype? DnD 5e

### ISSUE THREAD

**Issue by KnightGabriel** [PCGen/pcgen#7035]
I loaded the "System Reference Document 5.1"(because that was literally the only dnd 5e source seemingly available), I want to select the eldritch knight archetype, but I can not for the life of me find out how to actually select it. There doesn't seem to be ANY form of way to choose an archetype, google was completely and utterly useless, and it's driving me crazy. How do I select archetypes? Do I need to download anything else?

**Comment by LegacyKing** [comment]
The SRD5.1 doesn't include the archetype, it's a rather limited version with one or two choices per item. Off the top of my head, I'm aware of one homebrew set that includes what you're looking for, but it's not official PCGen so we don't support it.  https://github.com/BahamutDragon/pcgen

Good luck!
