### ISSUE TITLE
[BUG] (data) Shaman when the receive wandering hex should get +1 domain

### ISSUE THREAD

**Issue by xenusuk1** [PCGen/pcgen#7106]
given you are levelling a Shaman
when the Shaman receives the wandering spirit class feature
then the shaman should also receive +1 domain
so that the domain matching the wandering spirit can be applied and those domain spells made available

**To Reproduce**
The shaman receives wandering spirit at 4th level
the shaman can select the wandering spirit
the shaman does not receive +1 domain
so that you are unable to select the domain matching for the domain spells (the spirit domains are already present but only 1 can be selected)

**Expected behavior**
The shaman should receive +1 domain when gaining wandering spirit

**Desktop (please complete the following information):**
pcgen 6.09.05

**Character File**
Include a character *.pcg file that can be used to reproduce the issue.

**Additional context**

**Comment by LegacyKing** [comment]
I'll grant the spells, but there are no domains for a shaman. Same issue with spells, until the character is saved, closed and reopened the spells will not display.
