### ISSUE TITLE
PObject Spear of the Honored Ancestors not found

### ISSUE THREAD

**Issue by Laski** [PCGen/pcgen#956]
Weapon Master's Handbook seems to have a bug (or a dependency not listed)

07:12:45.156 INFO Thread-3 SourceFileLoader:518 Loading game Pathfinder_RPG and sources [Advanced Class Guide, Advanced Player's Guide, Advanced Race Guide, Adventurer's Armory, Andoran, Spirit of Liberty, Animal Archive, Bestiary, Bestiary 2, Bestiary 3, Blood of Angels, Blood of Fiends, Blood of the Moon, Cheliax, Empire of Devils, Core Rulebook, Dragon Empires Gazetteer, Dragon Empires Primer, Dungeoneer's Handbook, Dwarves of Golarion, Faiths of Balance, Faiths of Corruption, Faiths of Purity, Gnomes of Golarion, Goblins of Golarion, Guide to the River Kingdoms, Halflings of Golarion, Heart of the Jungle, Humans of Golarion, Inner Sea Bestiary, Inner Sea Combat, Inner Sea Primer, Inner Sea World Guide, Lords of Chaos - Book of the Damned, Volume 2, Orcs of Golarion, Pathfinder Campaign Setting: Distant Worlds, Pirates of the Inner Sea, Princes of Darkness - Book of the Damned, Volume 1, Qadira, Gateway to the East, Rise of the Runelords Player's Guide (Anniversary Edition), Sargava the Lost Colony, Ultimate Campaign, Ultimate Combat, Ultimate Equipment, Ultimate Magic, Varisia, Birthplace of Legends, Pathfinder Unchained, Weapon Master's Handbook].
07:12:53.555 LSTERROR Thread-3 LstObjectFileLoader:644 file:.../pcgen/data/pathfinder/paizo/player_companion/weapon_masters_handbook/wmh_equip.lst (20): PObject Spear of the Honored Ancestors not found; .MOD skipped.
07:13:03.884 SEVERE Thread-3 SortKeyToken:108 SORTKEY sorting in PaperInfo did not match file order

**Comment by oiml** [comment]
PR submitted, should load correctly now.

**Comment by LegacyKing** [comment]
Congrats. First ever bug entry through github for our group. Normally we ask people to use our much more feature rich jira system - pcgenorg.atlassian.net for bug issues. But thanks all the same. Issue is now fixed.

**Comment by Laski** [comment]
Thank you! That's some big honor :yum:
